GPower Environmental Monitor: SensorRegistry Class Reference
SensorRegistry Class Reference
Sensor Management » Sensor Registry
Registry for managing sensor instances This class maintains collections of sensors organized by their capabilities, allowing for efficient lookup by type or name.
#include <SensorRegistry.h>
Public Member Functions
SensorRegistry (ErrorHandler *err)
Constructor for SensorRegistry.
~SensorRegistry ()
Destructor Note: This does not delete the sensor instances, as they are owned by SensorManager.
void registerSensor (ISensor *sensor)
Register a sensor in the registry Adds a sensor to the registry, making it available for lookup by name or type.
ISensor * unregisterSensor (const String &sensorName)
Unregister a sensor from the registry by name Removes a sensor from the registry, but does not delete it.
std::vector< ISensor * > clear ()
Clear all sensors from the registry Removes all sensors from the registry, but does not delete them.
std::vector< ISensor * > getAllSensors () const
Get all sensors in the registry.
std::vector< ITemperatureSensor * > getTemperatureSensors () const
Get all temperature sensors Returns all sensors that implement the ITemperatureSensor interface.
std::vector< IHumiditySensor * > getHumiditySensors () const
Get all humidity sensors Returns all sensors that implement the IHumiditySensor interface.
ISensor * getSensorByName (const String &name) const
Get a sensor by name.
bool hasSensor (const String &name) const
Check if a sensor with the given name exists in the registry.
size_t count () const
Get the number of sensors in the registry.
Private Member Functions
template<typename T>
T * getInterfaceFrom (ISensor *sensor, InterfaceType type) const
Helper to get a specific interface from a sensor if supported.
Private Attributes
std::vector< ISensor * > allSensors
List of all sensor instances.
ErrorHandler * errorHandler
Error handler for logging.
Detailed Description
Registry for managing sensor instances This class maintains collections of sensors organized by their capabilities, allowing for efficient lookup by type or name.
It serves as a central repository for all active sensors in the system.
Definition at line 29 of file SensorRegistry.h.
Constructor & Destructor Documentation
SensorRegistry()
SensorRegistry::SensorRegistry (ErrorHandler * err)
Constructor for SensorRegistry.
Parameters
err Pointer to the error handler for logging
Definition at line 3 of file SensorRegistry.cpp.
                                                : errorHandler(err) {
}
References errorHandler.
~SensorRegistry()
SensorRegistry::~SensorRegistry ()
Destructor Note: This does not delete the sensor instances, as they are owned by SensorManager.
Definition at line 6 of file SensorRegistry.cpp.
{
    // Note: We don't own the sensors, so we don't delete them
    allSensors.clear();
}
References allSensors.
Member Function Documentation
clear()
std::vector< ISensor * > SensorRegistry::clear ()
Clear all sensors from the registry Removes all sensors from the registry, but does not delete them.
Returns
Vector of all sensors that were in the registry
Definition at line 50 of file SensorRegistry.cpp.
{
    std::vector<ISensor*> sensors = allSensors;
    allSensors.clear();
    errorHandler->logError(INFO, "Cleared all sensors from registry");
    return sensors;
}
References allSensors, errorHandler, and INFO.
count()
size_t SensorRegistry::count () const
Get the number of sensors in the registry.
Returns
The number of sensors
Definition at line 105 of file SensorRegistry.cpp.
{
    return allSensors.size();
}
References allSensors.
getAllSensors()
std::vector< ISensor * > SensorRegistry::getAllSensors () const
Get all sensors in the registry.
Returns
Vector of all sensor pointers
Definition at line 58 of file SensorRegistry.cpp.
{
    return allSensors;
}
References allSensors.
getHumiditySensors()
std::vector< IHumiditySensor * > SensorRegistry::getHumiditySensors () const
Get all humidity sensors Returns all sensors that implement the IHumiditySensor interface.
Returns
Vector of humidity sensor pointers
Definition at line 77 of file SensorRegistry.cpp.
{
    std::vector<IHumiditySensor*> result;
    for (auto sensor : allSensors) {
        IHumiditySensor* humSensor = getInterfaceFrom<IHumiditySensor>(
            sensor, InterfaceType::HUMIDITY);
        if (humSensor) {
            result.push_back(humSensor);
        }
    }
    return result;
}
References allSensors, getInterfaceFrom(), and HUMIDITY.
getInterfaceFrom()
template<typename T> T * SensorRegistry::getInterfaceFrom (ISensor * sensor, InterfaceType type) const inline private
Helper to get a specific interface from a sensor if supported.
Template Parameters
T The interface type to get
Parameters
sensor The sensor to get the interface from
type The InterfaceType enum value
Returns
Pointer to the interface, or nullptr if not supported
Definition at line 49 of file SensorRegistry.h.
{
         if (sensor && sensor->supportsInterface(type)) {
             return static_cast<T*>(sensor->getInterface(type));
         }
         return nullptr;
     }
References ISensor::getInterface(), and ISensor::supportsInterface().
Referenced by getHumiditySensors(), and getTemperatureSensors().
getSensorByName()
ISensor * SensorRegistry::getSensorByName (const String & name) const
Get a sensor by name.
Parameters
name The name of the sensor to find
Returns
Pointer to the found sensor, or nullptr if not found
Definition at line 92 of file SensorRegistry.cpp.
{
    for (auto sensor : allSensors) {
        if (sensor->getName() == name) {
            return sensor;
        }
    }
    return nullptr;
}
References allSensors.
Referenced by hasSensor().
getTemperatureSensors()
std::vector< ITemperatureSensor * > SensorRegistry::getTemperatureSensors () const
Get all temperature sensors Returns all sensors that implement the ITemperatureSensor interface.
Returns
Vector of temperature sensor pointers
Definition at line 62 of file SensorRegistry.cpp.
{
    std::vector<ITemperatureSensor*> result;
    for (auto sensor : allSensors) {
        ITemperatureSensor* tempSensor = getInterfaceFrom<ITemperatureSensor>(
            sensor, InterfaceType::TEMPERATURE);
        if (tempSensor) {
            result.push_back(tempSensor);
        }
    }
    return result;
}
References allSensors, getInterfaceFrom(), and TEMPERATURE.
hasSensor()
bool SensorRegistry::hasSensor (const String & name) const
Check if a sensor with the given name exists in the registry.
Parameters
name The sensor name to check for
Returns
true if the sensor exists, false otherwise
Definition at line 101 of file SensorRegistry.cpp.
{
    return getSensorByName(name) != nullptr;
}
References getSensorByName().
Referenced by registerSensor().
registerSensor()
void SensorRegistry::registerSensor (ISensor * sensor)
Register a sensor in the registry Adds a sensor to the registry, making it available for lookup by name or type.
Parameters
sensor Pointer to the sensor to register
Definition at line 11 of file SensorRegistry.cpp.
{
    if (!sensor) {
        errorHandler->logError(ERROR, "Attempted to register null sensor");
        return;
    }
    // Check if sensor already exists
    if (hasSensor(sensor->getName())) {
        errorHandler->logError(WARNING, "Sensor with name " + sensor->getName() + " already exists in registry");
        return;
    }
    // Add to the general sensor list
    allSensors.push_back(sensor);
    errorHandler->logError(INFO, "Registered sensor: " + sensor->getName());
}
References allSensors, ERROR, errorHandler, ISensor::getName(), hasSensor(), INFO, and WARNING.
unregisterSensor()
ISensor * SensorRegistry::unregisterSensor (const String & sensorName)
Unregister a sensor from the registry by name Removes a sensor from the registry, but does not delete it.
Parameters
sensorName The name of the sensor to unregister
Returns
The unregistered sensor pointer, or nullptr if not found
Definition at line 29 of file SensorRegistry.cpp.
{
    ISensor* sensorToRemove = nullptr;
    // Find the sensor
    for (auto it = allSensors.begin(); it != allSensors.end(); ++it) {
        if ((*it)->getName() == sensorName) {
            sensorToRemove = *it;
            allSensors.erase(it);
            break;
        }
    }
    if (!sensorToRemove) {
        errorHandler->logError(WARNING, "Attempted to unregister non-existent sensor: " + sensorName);
        return nullptr;
    }
    errorHandler->logError(INFO, "Unregistered sensor: " + sensorName);
    return sensorToRemove;
}
References allSensors, errorHandler, INFO, and WARNING.
Member Data Documentation
allSensors
std::vector<ISensor*> SensorRegistry::allSensors private
List of all sensor instances.
Definition at line 34 of file SensorRegistry.h.
Referenced by clear(), count(), getAllSensors(), getHumiditySensors(), getSensorByName(), getTemperatureSensors(), registerSensor(), unregisterSensor(), and ~SensorRegistry().
errorHandler
ErrorHandler* SensorRegistry::errorHandler private
Error handler for logging.
Definition at line 39 of file SensorRegistry.h.
Referenced by clear(), registerSensor(), SensorRegistry(), and unregisterSensor().
The documentation for this class was generated from the following files:
src/managers/SensorRegistry.h
src/managers/SensorRegistry.cpp