GPower Environmental Monitor: I2CManager Class Reference
I2CManager Class Reference
Communication » I2C Management
Manages I2C bus configurations and communication This class provides a central management system for I2C buses, handling bus initialization, device detection, and providing a unified interface for working with multiple I2C buses.
#include <I2CManager.h>
Public Member Functions
I2CManager (ErrorHandler *err)
Constructor for I2CManager Initializes the manager and registers default I2C buses.
~I2CManager ()
Destructor.
bool registerWire (I2CPort port, TwoWire *wire, int sdaPin, int sclPin, uint32_t clockFreq=100000)
Register a TwoWire instance for a specific I2C port Associates a TwoWire instance with a specific I2C port identifier and configures its pins and clock frequency.
bool begin ()
Initialize default I2C buses Initializes all registered I2C buses with their configured pin assignments and settings.
bool beginPort (I2CPort port)
Initialize a specific I2C bus Initializes only the specified I2C bus with its configured settings.
bool isPortInitialized (I2CPort port) const
Check if a specific I2C port is initialized.
bool scanBus (I2CPort port, std::vector< int > &addresses)
Scan an I2C bus for devices Scans the specified I2C bus for connected devices and returns a list of discovered I2C addresses.
TwoWire * getWire (I2CPort port)
Get the TwoWire object for a specific I2C port.
const WireConfig * getWireConfig (I2CPort port) const
Get the configuration for a specific I2C port.
bool devicePresent (I2CPort port, int address)
Check if a device is present at the specified address on a specific I2C port.
Static Public Member Functions
static I2CPort stringToPort (const String &portName)
Convert a string port name to I2CPort enum.
static String portToString (I2CPort port)
Convert I2CPort enum to string.
Private Attributes
std::map< I2CPort, WireConfig > wireBuses
Map of I2C port identifiers to their configurations.
ErrorHandler * errorHandler
Error handler for logging and error reporting.
Detailed Description
Manages I2C bus configurations and communication This class provides a central management system for I2C buses, handling bus initialization, device detection, and providing a unified interface for working with multiple I2C buses.
Definition at line 68 of file I2CManager.h.
Constructor & Destructor Documentation
I2CManager()
I2CManager::I2CManager (ErrorHandler * err)
Constructor for I2CManager Initializes the manager and registers default I2C buses.
Parameters
err Pointer to the error handler for logging
Definition at line 3 of file I2CManager.cpp.
                                        : errorHandler(err) {
    // Register default Wire instances
    // Main I2C bus - traditional Arduino pins
    registerWire(I2CPort::I2C0, &Wire1, 7, 6);  // GPIO7 (SDA), GPIO6 (SCL)
    // STEMMA QT / Qwiic connector
    registerWire(I2CPort::I2C1, &Wire, 41, 40); // GPIO41 (SDA), GPIO40 (SCL)
}
References errorHandler, I2C0, I2C1, and registerWire().
~I2CManager()
I2CManager::~I2CManager ()
Destructor.
Definition at line 12 of file I2CManager.cpp.
{
    // Nothing to clean up
}
Member Function Documentation
begin()
bool I2CManager::begin ()
Initialize default I2C buses Initializes all registered I2C buses with their configured pin assignments and settings.
Returns
true if at least one bus was initialized, false if all failed
Definition at line 28 of file I2CManager.cpp.
                       {
    // Initialize all registered buses
    bool atLeastOneSuccess = false;
    for (auto& pair : wireBuses) {
        I2CPort port = pair.first;
        bool success = beginPort(port);
        atLeastOneSuccess |= success;
    }
    return atLeastOneSuccess;
}
References beginPort(), and wireBuses.
beginPort()
bool I2CManager::beginPort (I2CPort port)
Initialize a specific I2C bus Initializes only the specified I2C bus with its configured settings.
Parameters
port The I2C port to initialize
Returns
true if initialization succeeded, false otherwise
Definition at line 41 of file I2CManager.cpp.
{
    auto it = wireBuses.find(port);
    if (it == wireBuses.end()) {
        errorHandler->logError(ERROR, "No Wire instance registered for port " + portToString(port));
        return false;
    }
    WireConfig& config = it->second;
    // Skip if already initialized
    if (config.initialized) {
        return true;
    }
    // Initialize the Wire instance with the specified pins
    config.wire->begin(config.sdaPin, config.sclPin);
    // Set clock frequency if specified and different from default
    if (config.clockFrequency != 50000) {
        config.wire->setClock(config.clockFrequency);
    }
    config.initialized = true;
    errorHandler->logError(INFO, "I2C port " + portToString(port) + " initialized with pins SDA:" +
                         String(config.sdaPin) + " SCL:" + String(config.sclPin));
    return true;
}
References WireConfig::clockFrequency, ERROR, errorHandler, INFO, WireConfig::initialized, portToString(), WireConfig::sclPin, WireConfig::sdaPin, WireConfig::wire, and wireBuses.
Referenced by begin().
devicePresent()
bool I2CManager::devicePresent (I2CPort port, int address)
Check if a device is present at the specified address on a specific I2C port.
Parameters
port The I2C port to check
address The I2C address to check
Returns
true if a device is present, false otherwise
Definition at line 125 of file I2CManager.cpp.
{
    TwoWire* wire = getWire(port);
    if (!wire || !isPortInitialized(port)) {
        errorHandler->logError(ERROR, "I2C port " + portToString(port) + " not initialized");
        return false;
    }
    wire->beginTransmission(address);
    byte error = wire->endTransmission();
    return (error == 0);
}
References ERROR, errorHandler, getWire(), isPortInitialized(), and portToString().
Referenced by scanBus().
getWire()
TwoWire * I2CManager::getWire (I2CPort port)
Get the TwoWire object for a specific I2C port.
Parameters
port The I2C port
Returns
Pointer to the TwoWire object, or nullptr if not initialized
Definition at line 78 of file I2CManager.cpp.
{
    auto it = wireBuses.find(port);
    if (it == wireBuses.end()) {
        errorHandler->logError(ERROR, "No Wire instance registered for port " + portToString(port));
        return nullptr;
    }
    return it->second.wire;
}
References ERROR, errorHandler, portToString(), and wireBuses.
Referenced by devicePresent(), and scanBus().
getWireConfig()
const WireConfig * I2CManager::getWireConfig (I2CPort port) const
Get the configuration for a specific I2C port.
Parameters
port The I2C port
Returns
The WireConfig structure, or nullptr if not registered
Definition at line 88 of file I2CManager.cpp.
{
    auto it = wireBuses.find(port);
    if (it == wireBuses.end()) {
        return nullptr;
    }
    return &(it->second);
}
References wireBuses.
isPortInitialized()
bool I2CManager::isPortInitialized (I2CPort port) const
Check if a specific I2C port is initialized.
Parameters
port The I2C port to check
Returns
true if the port is initialized, false otherwise
Definition at line 69 of file I2CManager.cpp.
{
    auto it = wireBuses.find(port);
    if (it == wireBuses.end()) {
        return false;
    }
    return it->second.initialized;
}
References wireBuses.
Referenced by devicePresent(), and scanBus().
portToString()
String I2CManager::portToString (I2CPort port) static
Convert I2CPort enum to string.
Parameters
port The I2CPort enum value
Returns
The string representation of the port
Definition at line 156 of file I2CManager.cpp.
{
    int portValue = static_cast<int>(port);
    // Handle built-in ports
    switch (port) {
        case I2CPort::I2C0: return "I2C0";
        case I2CPort::I2C1: return "I2C1";
        default: break;
    }
    // Handle multiplexed ports
    if (portValue >= static_cast<int>(I2CPort::I2C_MULTIPLEXED_START)) {
        int channel = portValue - static_cast<int>(I2CPort::I2C_MULTIPLEXED_START);
        return "I2C_MUX_" + String(channel);
    }
    return "UNKNOWN";
}
References I2C0, I2C1, and I2C_MULTIPLEXED_START.
Referenced by beginPort(), SensorFactory::createI2CSensor(), SensorFactory::createSensor(), devicePresent(), SHT41Sensor::getSensorInfo(), Si7021Sensor::getSensorInfo(), getWire(), registerWire(), scanBus(), SensorManager::testI2CCommunication(), ConfigManager::updateSensorConfigFromJson(), and ConfigManager::updateSensorConfigs().
registerWire()
bool I2CManager::registerWire (I2CPort port, TwoWire * wire, int sdaPin, int sclPin, uint32_t clockFreq = 100000)
Register a TwoWire instance for a specific I2C port Associates a TwoWire instance with a specific I2C port identifier and configures its pins and clock frequency.
Parameters
port The I2C port identifier
wire Pointer to the TwoWire instance
sdaPin The SDA pin number for this bus
sclPin The SCL pin number for this bus
clockFreq The I2C clock frequency in Hz (default: 100kHz)
Returns
true if registration succeeded, false otherwise
Definition at line 16 of file I2CManager.cpp.
{
    if (!wire) {
        errorHandler->logError(ERROR, "Null Wire instance provided for port " + portToString(port));
        return false;
    }
    wireBuses[port] = WireConfig(wire, sdaPin, sclPin, clockFreq);
    errorHandler->logError(INFO, "Registered Wire instance for port " + portToString(port) +
                         " with pins SDA:" + String(sdaPin) + " SCL:" + String(sclPin));
    return true;
}
References ERROR, errorHandler, INFO, portToString(), and wireBuses.
Referenced by I2CManager().
scanBus()
bool I2CManager::scanBus (I2CPort port, std::vector< int > & addresses)
Scan an I2C bus for devices Scans the specified I2C bus for connected devices and returns a list of discovered I2C addresses.
Parameters
port The I2C port to scan
addresses Output vector that will be filled with found addresses
Returns
true if at least one device was found, false otherwise
Definition at line 97 of file I2CManager.cpp.
{
    TwoWire* wire = getWire(port);
    if (!wire || !isPortInitialized(port)) {
        errorHandler->logError(ERROR, "I2C port " + portToString(port) + " not initialized before scan");
        return false;
    }
    addresses.clear();
    errorHandler->logError(INFO, "Scanning I2C port " + portToString(port) + "...");
    for (int address = 1; address < 127; address++) {
        if (devicePresent(port, address)) {
            addresses.push_back(address);
            errorHandler->logError(INFO, "Found I2C device at address 0x" + String(address, HEX) +
                              " on port " + portToString(port));
        }
    }
    if (addresses.empty()) {
        errorHandler->logError(INFO, "No I2C devices found on port " + portToString(port));
        return false;
    }
    errorHandler->logError(INFO, "Found " + String(addresses.size()) + " I2C devices on port " +
                      portToString(port));
    return true;
}
References devicePresent(), ERROR, errorHandler, getWire(), INFO, isPortInitialized(), and portToString().
stringToPort()
I2CPort I2CManager::stringToPort (const String & portName) static
Convert a string port name to I2CPort enum.
Parameters
portName The string port name (e.g., "I2C0", "I2C1")
Returns
The corresponding I2CPort enum value
Definition at line 138 of file I2CManager.cpp.
{
    // Handle existing port names
    if (portName.equalsIgnoreCase("I2C0")) {
        return I2CPort::I2C0;
    } else if (portName.equalsIgnoreCase("I2C1")) {
        return I2CPort::I2C1;
    }
    // #TODO Handle multiplexed ports if format is like "I2C_MUX_0", "I2C_MUX_1", etc.
    if (portName.startsWith("I2C_MUX_")) {
        String channelStr = portName.substring(8);
        int channel = channelStr.toInt();
        return static_cast<I2CPort>(static_cast<int>(I2CPort::I2C_MULTIPLEXED_START) + channel);
    }
    // Default to I2C0 if unrecognized
    return I2CPort::I2C0;
}
References I2C0, I2C1, and I2C_MULTIPLEXED_START.
Referenced by ConfigManager::loadConfigFromFile(), SensorManager::reconfigureSensors(), and ConfigManager::updateSensorConfigFromJson().
Member Data Documentation
errorHandler
ErrorHandler* I2CManager::errorHandler private
Error handler for logging and error reporting.
Definition at line 78 of file I2CManager.h.
Referenced by beginPort(), devicePresent(), getWire(), I2CManager(), registerWire(), and scanBus().
wireBuses
std::map<I2CPort, WireConfig> I2CManager::wireBuses private
Map of I2C port identifiers to their configurations.
Definition at line 73 of file I2CManager.h.
Referenced by begin(), beginPort(), getWire(), getWireConfig(), isPortInitialized(), and registerWire().
The documentation for this class was generated from the following files:
src/managers/I2CManager.h
src/managers/I2CManager.cpp