GPower Environmental Monitor: CommunicationManager Class Reference
CommunicationManager Class Reference
Communication
Manages communication with external systems using SCPI commands Processes incoming commands through both a custom command handler and SCPI parser, providing a unified interface for controlling the device via serial.
#include <CommunicationManager.h>
Public Member Functions
CommunicationManager (SensorManager *sensorMgr, ConfigManager *configMgr, ErrorHandler *err, LedManager *led=nullptr)
Constructor for CommunicationManager.
void begin (long baudRate)
Initialize the communication system.
void setupCommands ()
Register all SCPI commands with the parser.
void processIncomingData ()
Process incoming serial data and handle complete commands.
void setLedManager (LedManager *led)
Set the LED manager.
void processCommandLine ()
Process a single incoming command line.
void parseCommand (const String &rawCommand, String &command, std::vector< String > &params)
Parse a raw command string into command and parameters.
bool processCommand (const String &command, const std::vector< String > &params)
Process a command using the registered handler.
Command handlers
bool handleIdentify (const std::vector< String > &params)
Handle device identification command (*IDN?)
bool handleMeasure (const std::vector< String > &params)
Handle measurement query command (MEAS?)
bool handleListSensors (const std::vector< String > &params)
Handle sensor listing command (SYST:SENS:LIST?)
bool handleGetConfig (const std::vector< String > &params)
Handle configuration query command (SYST:CONF?)
bool handleSetBoardId (const std::vector< String > &params)
Handle board ID setting command (SYST:CONF:BOARD:ID)
bool handleUpdateConfig (const std::vector< String > &params)
Handle configuration update command (SYST:CONF:UPDATE)
bool handleUpdateSensorConfig (const std::vector< String > &params)
Handle sensor configuration update command (SYST:CONF:SENS:UPDATE)
bool handleUpdateAdditionalConfig (const std::vector< String > &params)
Handle additional configuration update command (SYST:CONF:ADD:UPDATE)
bool handleReset (const std::vector< String > &params)
Handle reset command (RESET)
bool handleTestFilesystem (const std::vector< String > &params)
Handle filesystem test command (TEST:FS)
bool handleTestUpdateConfig (const std::vector< String > &params)
Handle configuration update test command (TEST:UPDATE)
bool handleEcho (const std::vector< String > &params)
Handle echo command (ECHO)
bool handleLogRouting (const std::vector< String > &params)
Handle log routing command (SYST:LOG)
bool handleLogStatus (const std::vector< String > &params)
Handle log status query command (SYST:LOG?)
bool handleLedIdentify (const std::vector< String > &params)
Handle LED identification command (SYST:LED:IDENT)
bool handleTestErrorLevel (const std::vector< String > &params, ErrorSeverity severity)
Handle test error level commands.
bool handleTestInfoLevel (const std::vector< String > &params)
Handle test info level command (TEST:INFO)
bool handleTestWarningLevel (const std::vector< String > &params)
Handle test warning level command (TEST:WARNING)
bool handleTestErrorLevel (const std::vector< String > &params)
Handle test error level command (TEST:ERROR)
bool handleTestFatalLevel (const std::vector< String > &params)
Handle test fatal level command (TEST:FATAL)
Private Member Functions
~CommunicationManager ()
Destructor - cleans up allocated resources.
void registerCommandHandlers ()
Register all commands with their handlers.
void collectSensorReadings (const String &sensorName, const String &measurements, std::vector< String > &values)
Collect readings from a sensor into a values vector.
Private Attributes
SCPI_Parser * scpiParser
SCPI parser instance.
std::map< String, CommandHandler > commandHandlers
Map of command strings to handler functions.
SensorManager * sensorManager
References to other system managers.
ConfigManager * configManager
ErrorHandler * errorHandler
LedManager * ledManager = nullptr
Static Private Attributes
static Print * uartDebugSerial = nullptr
Static reference to UART debug serial.
static CommunicationManager * instance = nullptr
Singleton instance for callback access.
Static and accessor methods
SensorManager * getSensorManager ()
Get the sensor manager.
ConfigManager * getConfigManager ()
Get the configuration manager.
ErrorHandler * getErrorHandler ()
Get the error handler.
SCPI_Parser * getScpiParser ()
Get the SCPI parser.
static CommunicationManager * getInstance ()
Get singleton instance.
static void setUartDebugSerialPtr (Print *debugSerial)
Set the UART debug serial pointer for message routing.
Detailed Description
Manages communication with external systems using SCPI commands Processes incoming commands through both a custom command handler and SCPI parser, providing a unified interface for controlling the device via serial.
Supports custom command processing and SCPI standards compliance.
Definition at line 43 of file CommunicationManager.h.
Constructor & Destructor Documentation
~CommunicationManager()
CommunicationManager::~CommunicationManager () private
Destructor - cleans up allocated resources.
Definition at line 23 of file CommunicationManager.cpp.
{
    delete scpiParser;
}
References scpiParser.
CommunicationManager()
CommunicationManager::CommunicationManager (SensorManager * sensorMgr, ConfigManager * configMgr, ErrorHandler * err, LedManager * led = nullptr)
Constructor for CommunicationManager.
Parameters
sensorMgr Pointer to sensor manager
configMgr Pointer to configuration manager
err Pointer to error handler
led Optional pointer to LED manager
Definition at line 13 of file CommunicationManager.cpp.
                                                                                                                                 :
    sensorManager(sensorMgr),
    configManager(configMgr),
    errorHandler(err),
    ledManager(led) {
    instance = this;
    scpiParser = new SCPI_Parser();
}
References configManager, errorHandler, instance, ledManager, scpiParser, and sensorManager.
Referenced by getInstance().
Member Function Documentation
begin()
void CommunicationManager::begin (long baudRate)
Initialize the communication system.
Parameters
baudRate Serial communication baud rate
Definition at line 27 of file CommunicationManager.cpp.
{
    errorHandler->logError(INFO, "Communication manager initialized");
    registerCommandHandlers();
}
References errorHandler, INFO, and registerCommandHandlers().
collectSensorReadings()
void CommunicationManager::collectSensorReadings (const String & sensorName, const String & measurements, std::vector< String > & values) private
Collect readings from a sensor into a values vector.
Parameters
sensorName The name of the sensor to read from
measurements The measurements to read (comma-separated or empty for all)
values Vector to collect the values into
Definition at line 391 of file CommunicationManager.cpp.
{
    // Constants for retry logic
    const int MAX_RETRIES = Constants::Communication::MAX_READING_RETRIES;
    const int RETRY_DELAY_MS = Constants::Communication::READING_RETRY_DELAY_MS;
    // Find the sensor
    ISensor* sensor = sensorManager->findSensor(sensorName);
    bool sensorOk = (sensor != nullptr && sensor->isConnected());
    if (!sensorOk) {
        errorHandler->logError(WARNING, "Peripheral " + sensorName + " not found or not connected");
        return;
    }
    // Determine which measurements to take
    bool useAllMeasurements = measurements.length() == 0;
    String upperMeasurements = measurements;
    upperMeasurements.toUpperCase();
    bool readTemp = useAllMeasurements || upperMeasurements.indexOf("TEMP") >= 0;
    bool readHum = useAllMeasurements || upperMeasurements.indexOf("HUM") >= 0;
    // Read temperature if requested and supported
    if (readTemp && sensorOk && sensor->supportsInterface(InterfaceType::TEMPERATURE)) {
        // Try first reading without any delay
        TemperatureReading tempReading = sensorManager->getTemperatureSafe(sensorName);
        if (tempReading.valid) {
            // Fast path - reading succeeded on first try (most common case)
            values.push_back(String(tempReading.value));
        } else {
            // Only if first read failed, apply retry logic with delays
            bool success = false;
            String tempValue = "ERROR";
            for (int attempt = 1; attempt < MAX_RETRIES && !success; attempt++) {
                // Log retry information at INFO level
                errorHandler->logError(INFO, "Retry #" + String(attempt) + " for temperature reading from " + sensorName);
                delay(RETRY_DELAY_MS); // Only delay during retries when needed
                try {
                    tempReading = sensorManager->getTemperatureSafe(sensorName);
                    if (tempReading.valid) {
                        tempValue = String(tempReading.value);
                        success = true;
                        errorHandler->logError(INFO, "Successfully read temperature from " + sensorName + " after " + String(attempt+1) + " attempts");
                        break;
                    }
                } catch (...) {
                    // Continue to next retry attempt
                }
            }
            values.push_back(success ? tempValue : "ERROR");
        }
    }
    // Read humidity if requested and supported
    if (readHum && sensorOk && sensor->supportsInterface(InterfaceType::HUMIDITY)) {
        // Try first reading without any delay
        HumidityReading humReading = sensorManager->getHumiditySafe(sensorName);
        if (humReading.valid) {
            // Fast path - reading succeeded on first try (most common case)
            values.push_back(String(humReading.value));
        } else {
            // Only if first read failed, apply retry logic with delays
            bool success = false;
            String humValue = "ERROR";
            for (int attempt = 1; attempt < MAX_RETRIES && !success; attempt++) {
                // Log retry information at INFO level
                errorHandler->logError(INFO, "Retry #" + String(attempt) + " for humidity reading from " + sensorName);
                delay(RETRY_DELAY_MS); // Only delay during retries when needed
                try {
                    humReading = sensorManager->getHumiditySafe(sensorName);
                    if (humReading.valid) {
                        humValue = String(humReading.value);
                        success = true;
                        errorHandler->logError(INFO, "Successfully read humidity from " + sensorName + " after " + String(attempt+1) + " attempts");
                        break;
                    }
                } catch (...) {
                    // Continue to next retry attempt
                }
            }
            values.push_back(success ? humValue : "ERROR");
        }
    }
}
References errorHandler, HUMIDITY, INFO, ISensor::isConnected(), Constants::Communication::MAX_READING_RETRIES, Constants::Communication::READING_RETRY_DELAY_MS, sensorManager, ISensor::supportsInterface(), TEMPERATURE, HumidityReading::valid, TemperatureReading::valid, HumidityReading::value, TemperatureReading::value, and WARNING.
Referenced by handleMeasure().
getConfigManager()
ConfigManager * CommunicationManager::getConfigManager ()
Get the configuration manager.
Returns
Pointer to the configuration manager
Definition at line 767 of file CommunicationManager.cpp.
{
    return configManager;
}
References configManager.
getErrorHandler()
ErrorHandler * CommunicationManager::getErrorHandler ()
Get the error handler.
Returns
Pointer to the error handler
Definition at line 771 of file CommunicationManager.cpp.
{
    return errorHandler;
}
References errorHandler.
getInstance()
CommunicationManager * CommunicationManager::getInstance () static
Get singleton instance.
Returns
Pointer to the singleton instance
Definition at line 759 of file CommunicationManager.cpp.
{
    return instance;
}
References CommunicationManager(), and instance.
getScpiParser()
SCPI_Parser * CommunicationManager::getScpiParser () inline
Get the SCPI parser.
Returns
Pointer to the SCPI parser
Definition at line 327 of file CommunicationManager.h.
{ return scpiParser; }
References scpiParser.
getSensorManager()
SensorManager * CommunicationManager::getSensorManager ()
Get the sensor manager.
Returns
Pointer to the sensor manager
Definition at line 763 of file CommunicationManager.cpp.
{
    return sensorManager;
}
References sensorManager.
handleEcho()
bool CommunicationManager::handleEcho (const std::vector< String > & params)
Handle echo command (ECHO)
Parameters
params Text to echo
Returns
true if command processed successfully
Definition at line 634 of file CommunicationManager.cpp.
{
    String message = params.empty() ? "ECHO" : params[0];
    Serial.println("ECHO: " + message);
    return true;
}
Referenced by registerCommandHandlers(), and setupCommands().
handleGetConfig()
bool CommunicationManager::handleGetConfig (const std::vector< String > & params)
Handle configuration query command (SYST:CONF?)
Parameters
params Command parameters (not used)
Returns
true if command processed successfully
Definition at line 519 of file CommunicationManager.cpp.
{
    String config = configManager->getConfigJson();
    Serial.println(config);
    return true;
}
References configManager.
Referenced by registerCommandHandlers(), and setupCommands().
handleIdentify()
bool CommunicationManager::handleIdentify (const std::vector< String > & params)
Handle device identification command (*IDN?)
Parameters
params Command parameters (not used)
Returns
true if command processed successfully
Definition at line 309 of file CommunicationManager.cpp.
{
    String response = String(Constants::PRODUCT_NAME) + "," +
                      configManager->getBoardIdentifier() + "," +
                      String(Constants::FIRMWARE_VERSION);
    Serial.println(response);
    Serial.flush(); // Ensure the response is sent immediately
    return true;
}
References configManager, Constants::FIRMWARE_VERSION, and Constants::PRODUCT_NAME.
Referenced by registerCommandHandlers(), and setupCommands().
handleLedIdentify()
bool CommunicationManager::handleLedIdentify (const std::vector< String > & params)
Handle LED identification command (SYST:LED:IDENT)
Parameters
params Command parameters (not used)
Returns
true if command processed successfully
Definition at line 701 of file CommunicationManager.cpp.
{
    if (ledManager) {
        ledManager->startIdentify();
        errorHandler->logError(INFO, "identify mode activated");
    } else {
        errorHandler->logError(ERROR, "LED manager not available");
        return false;
    }
    return true;
}
References ERROR, errorHandler, INFO, and ledManager.
Referenced by registerCommandHandlers(), and setupCommands().
handleListSensors()
bool CommunicationManager::handleListSensors (const std::vector< String > & params)
Handle sensor listing command (SYST:SENS:LIST?)
Parameters
params Command parameters (not used)
Returns
true if command processed successfully
Definition at line 486 of file CommunicationManager.cpp.
{
    auto registry = sensorManager->getRegistry();
    auto sensors = registry.getAllSensors();
    // Build the complete response string first instead of sending it line by line
    String response = "";
    for (auto sensor : sensors) {
        // Check each interface type and output a separate entry for each
        if (sensor->supportsInterface(InterfaceType::TEMPERATURE)) {
            response += sensor->getName() + ",TEMP," +
                      sensor->getTypeString() + "," +
                      (sensor->isConnected() ? "CONNECTED" : "DISCONNECTED") + "\n";
        }
        if (sensor->supportsInterface(InterfaceType::HUMIDITY)) {
            response += sensor->getName() + ",HUM," +
                      sensor->getTypeString() + "," +
                      (sensor->isConnected() ? "CONNECTED" : "DISCONNECTED") + "\n";
        }
    }
    // Send the complete response all at once
    Serial.print(response);
    // Small delay to ensure all data is sent
    delay(5);
    // Flush to ensure all data is transmitted
    Serial.flush();
    return true;
}
References HUMIDITY, sensorManager, and TEMPERATURE.
Referenced by registerCommandHandlers(), and setupCommands().
handleLogRouting()
bool CommunicationManager::handleLogRouting (const std::vector< String > & params)
Handle log routing command (SYST:LOG)
Parameters
params Destination and severity parameters
Returns
true if command processed successfully
Definition at line 647 of file CommunicationManager.cpp.
{
    if (params.empty()) {
        errorHandler->logError(ERROR, "Format is SYST:LOG <destination>,<severity>");
        return false;
    }
    // Check if the parameters are in a single comma-separated string or in two separate parameters
    String destination, severityStr;
    if (params.size() == 1 && params[0].indexOf(',') > 0) {
        // Format: "USB,INFO" (comma-separated in a single parameter)
        int commaPos = params[0].indexOf(',');
        destination = params[0].substring(0, commaPos);
        severityStr = params[0].substring(commaPos + 1);
    } else if (params.size() >= 2) {
        // Format: "USB" "INFO" (two separate parameters)
        destination = params[0];
        severityStr = params[1];
    } else {
        errorHandler->logError(ERROR, "Format is SYST:LOG <destination>,<severity>");
        return false;
    }
    destination.toUpperCase();
    severityStr.toUpperCase();
    // Determine the target stream based on destination
    Print* targetStream = nullptr;
    if (destination == "USB" || destination == "SERIAL") {
        targetStream = &Serial;
    } else if (destination == "UART" || destination == "DEBUG") {
        targetStream = uartDebugSerial;
    } else if (destination == "NONE" || destination == "OFF") {
        targetStream = nullptr;
    } else {
        errorHandler->logError(ERROR, "Invalid destination. Use USB, UART, or NONE");
        return false;
    }
    // Determine severity
    ErrorSeverity minSeverity = ErrorHandler::stringToSeverity(severityStr);
    // Enable custom routing if it's not already enabled
    errorHandler->enableCustomRouting(true);
    // Set the routing configuration
    errorHandler->setOutputSeverity(targetStream, minSeverity);
    errorHandler->logError(INFO, "Log routing updated: " + destination + " will show " +
                 ErrorHandler::severityToString(minSeverity) + " and higher");
    return true;
}
References ERROR, errorHandler, INFO, ErrorHandler::severityToString(), ErrorHandler::stringToSeverity(), and uartDebugSerial.
Referenced by registerCommandHandlers(), and setupCommands().
handleLogStatus()
bool CommunicationManager::handleLogStatus (const std::vector< String > & params)
Handle log status query command (SYST:LOG?)
Parameters
params Command parameters (not used)
Returns
true if command processed successfully
Definition at line 641 of file CommunicationManager.cpp.
{
    String status = errorHandler->getRoutingStatus();
    Serial.println(status);
    return true;
}
References errorHandler.
Referenced by registerCommandHandlers(), and setupCommands().
handleMeasure()
bool CommunicationManager::handleMeasure (const std::vector< String > & params)
Handle measurement query command (MEAS?)
Parameters
params Sensor and measurement parameters
Returns
true if command processed successfully
Definition at line 318 of file CommunicationManager.cpp.
{
    std::vector<String> values;
    try {
        if (params.empty()) {
            // No sensors specified, use all available
            auto registry = sensorManager->getRegistry();
            auto allSensors = registry.getAllSensors();
            errorHandler->logError(INFO, "MEAS: Collecting data from all " + String(allSensors.size()) + " available peripherals");
            for (auto sensor : allSensors) {
                collectSensorReadings(sensor->getName(), "", values);
            }
        } else {
            // Process parameters efficiently by batching lookups
            std::map<String, String> sensorRequests;
            // First pass: parse parameters and group by sensor name
            for (const auto& param : params) {
                // Check if parameter contains a colon (sensor:measurements format)
                int colonPos = param.indexOf(':');
                String sensorName, measurements;
                if (colonPos > 0) {
                    sensorName = param.substring(0, colonPos);
                    measurements = param.substring(colonPos + 1);
                    errorHandler->logError(INFO, "MEAS: Reading " + sensorName + " with measurements: " + measurements);
                } else {
                    sensorName = param;
                    measurements = "";
                    errorHandler->logError(INFO, "MEAS: Reading " + sensorName + " with all available measurements");
                }
                // Store most specific measurement request for each sensor
                if (sensorRequests.find(sensorName) == sensorRequests.end() ||
                    measurements.length() > sensorRequests[sensorName].length()) {
                    sensorRequests[sensorName] = measurements;
                }
            }
            // Second pass: collect data for each unique sensor
            for (const auto& [sensorName, measurements] : sensorRequests) {
                collectSensorReadings(sensorName, measurements, values);
            }
        }
        // Output a single CSV line with all collected values
        if (!values.empty()) {
            String csvLine = values[0];
            for (size_t i = 1; i < values.size(); i++) {
                csvLine += "," + values[i];
            }
            Serial.println(csvLine);
            Serial.flush(); // Ensure the response is sent immediately
            errorHandler->logError(INFO, "MEAS: CSV response sent with " + String(values.size()) + " values");
        } else {
            errorHandler->logError(WARNING, "MEAS: No measurement values were collected!");
            Serial.println("ERROR");
            Serial.flush();
        }
    } catch (...) {
        // Catch any other unforeseen errors
        errorHandler->logError(WARNING, "MEAS: Unexpected exception during measurement");
        Serial.println("ERROR");
        Serial.flush();
        return false;
    }
    return true;
}
References collectSensorReadings(), errorHandler, INFO, sensorManager, and WARNING.
Referenced by registerCommandHandlers(), and setupCommands().
handleReset()
bool CommunicationManager::handleReset (const std::vector< String > & params)
Handle reset command (RESET)
Parameters
params Command parameters (not used)
Returns
true if command processed successfully
Definition at line 614 of file CommunicationManager.cpp.
{
    errorHandler->logError(INFO, "Reset command received");
    Serial.println("Resetting device...");
    delay(100);  // Give time for the message to be sent
    ESP.restart();
    return true;
}
References errorHandler, and INFO.
Referenced by registerCommandHandlers().
handleSetBoardId()
bool CommunicationManager::handleSetBoardId (const std::vector< String > & params)
Handle board ID setting command (SYST:CONF:BOARD:ID)
Parameters
params Board ID parameter
Returns
true if command processed successfully
Definition at line 525 of file CommunicationManager.cpp.
{
    if (params.empty()) {
        errorHandler->logError(ERROR, "No board ID specified");
        return false;
    }
    bool success = configManager->setBoardIdentifier(params[0]);
    if (!success) {
        errorHandler->logError(ERROR, "Failed to update Board ID");
    }
    return success;
}
References configManager, ERROR, and errorHandler.
Referenced by registerCommandHandlers(), and setupCommands().
handleTestErrorLevel() [1/2]
bool CommunicationManager::handleTestErrorLevel (const std::vector< String > & params) inline
Handle test error level command (TEST:ERROR)
Parameters
params Command parameters
Returns
true if command processed successfully
Definition at line 284 of file CommunicationManager.h.
{ return handleTestErrorLevel(params, ERROR); }
References ERROR, and handleTestErrorLevel().
Referenced by handleTestErrorLevel().
handleTestErrorLevel() [2/2]
bool CommunicationManager::handleTestErrorLevel (const std::vector< String > & params, ErrorSeverity severity)
Handle test error level commands.
Parameters
params Command parameters
severity Error severity level
Returns
true if command processed successfully
Definition at line 712 of file CommunicationManager.cpp.
{
    String severityStr = ErrorHandler::severityToString(severity);
    String message = "Test " + severityStr + " message";
    if (params.size() > 0) {
        message = params[0];
    }
    // Log the message
    bool isFatal = errorHandler->logError(severity, message);
    // Extra direct LED control for debugging
    if (ledManager && severity >= WARNING) {
        if (severity == WARNING) ledManager->indicateWarning();
        if (severity == ERROR) ledManager->indicateError();
        if (severity == FATAL) ledManager->indicateFatalError();
    }
    // For FATAL errors, handle specially
    if (isFatal) {
        // For FATAL, we might want to reset after some delay
        int resetDelay = -1;
        if (params.size() > 1) {
            resetDelay = params[1].toInt();
        }
        if (resetDelay > 0) {
            errorHandler->logError(FATAL, "Device will reset after " + String(resetDelay) + "ms");
            Serial.flush();
            delay(resetDelay);
            ESP.restart();
        } else {
            errorHandler->logError(FATAL, "Fatal error - device halted");
            Serial.flush();
            // Enter infinite loop, but keep LED updated
            while (true) {
                if (ledManager) {
                    ledManager->update();
                }
                delay(100);
                yield();
            }
        }
    }
    return true;
}
References ERROR, errorHandler, FATAL, ledManager, ErrorHandler::severityToString(), and WARNING.
Referenced by handleTestFatalLevel(), handleTestInfoLevel(), handleTestWarningLevel(), registerCommandHandlers(), and setupCommands().
handleTestFatalLevel()
bool CommunicationManager::handleTestFatalLevel (const std::vector< String > & params) inline
Handle test fatal level command (TEST:FATAL)
Parameters
params Command parameters
Returns
true if command processed successfully
Definition at line 291 of file CommunicationManager.h.
{ return handleTestErrorLevel(params, FATAL); }
References FATAL, and handleTestErrorLevel().
Referenced by setupCommands().
handleTestFilesystem()
bool CommunicationManager::handleTestFilesystem (const std::vector< String > & params)
Handle filesystem test command (TEST:FS)
Parameters
params Command parameters (not used)
Returns
true if command processed successfully
Definition at line 622 of file CommunicationManager.cpp.
{
    // Implement filesystem test logic here (moved from original)
    // (Implementation omitted for brevity)
    return true;
}
Referenced by registerCommandHandlers(), and setupCommands().
handleTestInfoLevel()
bool CommunicationManager::handleTestInfoLevel (const std::vector< String > & params) inline
Handle test info level command (TEST:INFO)
Parameters
params Command parameters
Returns
true if command processed successfully
Definition at line 270 of file CommunicationManager.h.
{ return handleTestErrorLevel(params, INFO); }
References handleTestErrorLevel(), and INFO.
Referenced by setupCommands().
handleTestUpdateConfig()
bool CommunicationManager::handleTestUpdateConfig (const std::vector< String > & params)
Handle configuration update test command (TEST:UPDATE)
Parameters
params Command parameters (not used)
Returns
true if command processed successfully
Definition at line 628 of file CommunicationManager.cpp.
{
    // Implement config update test logic here (moved from original)
    // (Implementation omitted for brevity)
    return true;
}
Referenced by registerCommandHandlers(), and setupCommands().
handleTestWarningLevel()
bool CommunicationManager::handleTestWarningLevel (const std::vector< String > & params) inline
Handle test warning level command (TEST:WARNING)
Parameters
params Command parameters
Returns
true if command processed successfully
Definition at line 277 of file CommunicationManager.h.
{ return handleTestErrorLevel(params, WARNING); }
References handleTestErrorLevel(), and WARNING.
Referenced by setupCommands().
handleUpdateAdditionalConfig()
bool CommunicationManager::handleUpdateAdditionalConfig (const std::vector< String > & params)
Handle additional configuration update command (SYST:CONF:ADD:UPDATE)
Parameters
params Additional configuration JSON
Returns
true if command processed successfully
Definition at line 591 of file CommunicationManager.cpp.
{
    if (params.empty()) {
        errorHandler->logError(WARNING, "No additional configuration provided");
    }
    // Join all parameters since the JSON might have spaces
    String jsonConfig = "";
    for (const auto& param : params) {
        if (jsonConfig.length() > 0) jsonConfig += " ";
        jsonConfig += param;
    }
    errorHandler->logError(INFO, "Processing additional config update: " +
                         jsonConfig.substring(0, std::min(50, (int)jsonConfig.length())) +
                         (jsonConfig.length() > 50 ? "..." : ""));
    bool success = configManager->updateAdditionalConfigFromJson(jsonConfig);
    if (!success) {
        errorHandler->logError(ERROR, "Failed to update additional configuration");
    }
    return success;
}
References configManager, ERROR, errorHandler, INFO, and WARNING.
Referenced by registerCommandHandlers(), and setupCommands().
handleUpdateConfig()
bool CommunicationManager::handleUpdateConfig (const std::vector< String > & params)
Handle configuration update command (SYST:CONF:UPDATE)
Parameters
params Configuration JSON
Returns
true if command processed successfully
Definition at line 538 of file CommunicationManager.cpp.
{
    if (params.empty()) {
        errorHandler->logError(ERROR, "No configuration JSON provided");
    }
    // Join all parameters since the JSON might have spaces
    String jsonConfig = "";
    for (const auto& param : params) {
        if (jsonConfig.length() > 0) jsonConfig += " ";
        jsonConfig += param;
    }
    errorHandler->logError(INFO, "Processing config update: " + jsonConfig.substring(0, 50) + "...");
    bool success = configManager->updateConfigFromJson(jsonConfig);
    if (!success) {
        errorHandler->logError(ERROR, "Failed to update configuration");
    }
    return success;
}
References configManager, ERROR, errorHandler, and INFO.
Referenced by registerCommandHandlers(), and setupCommands().
handleUpdateSensorConfig()
bool CommunicationManager::handleUpdateSensorConfig (const std::vector< String > & params)
Handle sensor configuration update command (SYST:CONF:SENS:UPDATE)
Parameters
params Sensor configuration JSON
Returns
true if command processed successfully
Definition at line 558 of file CommunicationManager.cpp.
{
    if (params.empty()) {
        errorHandler->logError(WARNING, "No sensor configuration provided");
    }
    // Join all parameters since the JSON might have spaces
    String jsonConfig = "";
    for (const auto& param : params) {
        if (jsonConfig.length() > 0) jsonConfig += " ";
        jsonConfig += param;
    }
    errorHandler->logError(INFO, "Processing sensor config update: " +
                         jsonConfig.substring(0, std::min(50, (int)jsonConfig.length())) +
                         (jsonConfig.length() > 50 ? "..." : ""));
    bool success = configManager->updateSensorConfigFromJson(jsonConfig);
    if (!success) {
        errorHandler->logError(ERROR, "Failed to update sensor configuration");
        return false;
    }
    // Add this block to explicitly reinitialize the sensors
    errorHandler->logError(INFO, "Reinitializing peripherals with new configuration");
    if (sensorManager->initializeSensors()) {
        errorHandler->logError(INFO, "Successfully reinitialized peripherals with new configuration");
    } else {
        errorHandler->logError(ERROR, "Failed to reinitialize some peripherals after configuration update");
    }
    return true;
}
References configManager, ERROR, errorHandler, INFO, sensorManager, and WARNING.
Referenced by registerCommandHandlers(), and setupCommands().
parseCommand()
void CommunicationManager::parseCommand (const String & rawCommand, String & command, std::vector< String > & params)
Parse a raw command string into command and parameters.
Parameters
rawCommand The full command string
command Output parameter for the extracted command
params Output parameter for the extracted parameters
Definition at line 174 of file CommunicationManager.cpp.
{
    params.clear();
    // Extract command (up to first space)
    int spacePos = rawCommand.indexOf(' ');
    if (spacePos > 0) {
        command = rawCommand.substring(0, spacePos);
        // Extract space-separated parameters
        String paramsStr = rawCommand.substring(spacePos + 1);
        paramsStr.trim();
        // Split parameters
        while (paramsStr.length() > 0) {
            int nextSpace = paramsStr.indexOf(' ');
            if (nextSpace > 0) {
                params.push_back(paramsStr.substring(0, nextSpace));
                paramsStr = paramsStr.substring(nextSpace + 1);
                paramsStr.trim();
            } else {
                // Last parameter
                params.push_back(paramsStr);
                break;
            }
        }
    } else {
        command = rawCommand;
    }
}
Referenced by processCommandLine(), and processIncomingData().
processCommand()
bool CommunicationManager::processCommand (const String & command, const std::vector< String > & params)
Process a command using the registered handler.
Parameters
command The command to process
params The command parameters
Returns
true if command was found and processed successfully
Definition at line 204 of file CommunicationManager.cpp.
{
    auto it = commandHandlers.find(command);
    if (it != commandHandlers.end()) {
        return it->second(params);
    }
    return false;
}
References commandHandlers.
Referenced by processCommandLine(), and processIncomingData().
processCommandLine()
void CommunicationManager::processCommandLine ()
Process a single incoming command line.
Definition at line 212 of file CommunicationManager.cpp.
{
    // Increased timeout and buffer size
    constexpr unsigned long COMMAND_TIMEOUT_MS = Constants::Communication::COMMAND_TIMEOUT_MS;
    constexpr size_t MAX_BUFFER_SIZE = Constants::Communication::MAX_BUFFER_SIZE;
    // Read a complete command with timeout
    String rawCommand = "";
    unsigned long startTime = millis();
    // Read until newline, timeout, or buffer full
    while ((millis() - startTime < COMMAND_TIMEOUT_MS) && (rawCommand.length() < MAX_BUFFER_SIZE)) {
        if (Serial.available()) {
            char c = Serial.read();
            if (c == '\n' || c == '\r') {
                if (rawCommand.length() > 0) {
                    break; // Complete command found
                }
                // Else ignore empty lines
            } else {
                rawCommand += c;
            }
        }
        yield(); // Allow other tasks to run
    }
    // Check if we hit the buffer limit
    if (rawCommand.length() >= MAX_BUFFER_SIZE) {
        errorHandler->logError(ERROR, "Command exceeds buffer size limit of " + String(MAX_BUFFER_SIZE) + " characters");
    }
    if (rawCommand.length() == 0) {
        return; // No command to process
    }
    // Trim whitespace and process command
    rawCommand.trim();
    errorHandler->logError(INFO, "Processing command: '" +
                         (rawCommand.length() > 50 ?
                            rawCommand.substring(0, 50) + "..." :
                            rawCommand) +
                         "' (" + String(rawCommand.length()) + " bytes)");
    // Parse and process command
    String command;
    std::vector<String> params;
    parseCommand(rawCommand, command, params);
    // Track if the command was recognized by either system
    bool commandRecognized = false;
    // Try to handle with our command processors
    if (processCommand(command, params)) {
        commandRecognized = true;
    } else {
        // Before falling back to SCPI parser, check if it's a HELP request
        if (command.equalsIgnoreCase("HELP") || command.equalsIgnoreCase("?")) {
            // Provide basic help information
            Serial.println("Available commands:");
            Serial.println("*IDN? - Get device identification");
            Serial.println("MEAS? - Get measurements from all peripherals");
            Serial.println("MEAS? <sensor>[:measurement] - Get specific measurements");
            Serial.println("SYST:SENS:LIST? - List all available peripherals");
            Serial.println("SYST:CONF? - Get device configuration");
            Serial.println("RESET - Reset the device");
            Serial.println();
            commandRecognized = true;
        } else {
            // Try SCPI parser as a fallback
            // Since we cannot easily detect if the SCPI parser recognized the command,
            // we'll capture the original Serial buffer position to see if anything was output
            size_t beforeSerialPos = Serial.availableForWrite();
            char buff[rawCommand.length() + 1];
            rawCommand.toCharArray(buff, rawCommand.length() + 1);
            scpiParser->ProcessInput(Serial, buff);
            // Check if SCPI parser generated any output
            size_t afterSerialPos = Serial.availableForWrite();
            if (afterSerialPos != beforeSerialPos) {
                commandRecognized = true;
            }
        }
    }
    // If the command wasn't recognized by either system, log a warning and send an error response
    if (!commandRecognized) {
        errorHandler->logError(ERROR, "Unrecognized command: '" +
                            (command.length() > 50 ?
                               command.substring(0, 50) + "..." :
                               command) + "'");
    }
    // Ensure all responses are sent
    Serial.flush();
}
References Constants::Communication::COMMAND_TIMEOUT_MS, ERROR, errorHandler, INFO, Constants::Communication::MAX_BUFFER_SIZE, parseCommand(), processCommand(), and scpiParser.
processIncomingData()
void CommunicationManager::processIncomingData ()
Process incoming serial data and handle complete commands.
Definition at line 146 of file CommunicationManager.cpp.
{
    // Check if there's data available in the serial buffer
    if (Serial.available() > 0) {
        // Read the entire line
        String rawCommand = Serial.readStringUntil('\n');
        rawCommand.trim();
        // Log receipt for debugging
        errorHandler->logError(INFO, "Processing command: '" + rawCommand + "'");
        // Parse and process command
        String command;
        std::vector<String> params;
        parseCommand(rawCommand, command, params);
        // Try to handle with our command processors
        if (!processCommand(command, params)) {
            // Fall back to SCPI parser for compatibility
            char buff[rawCommand.length() + 1];
            rawCommand.toCharArray(buff, rawCommand.length() + 1);
            scpiParser->ProcessInput(Serial, buff);
        }
        // Ensure all responses are sent
        Serial.flush();
    }
}
References errorHandler, INFO, parseCommand(), processCommand(), and scpiParser.
registerCommandHandlers()
void CommunicationManager::registerCommandHandlers () private
Register all commands with their handlers.
Definition at line 39 of file CommunicationManager.cpp.
{
    // Register command handlers
    commandHandlers[Constants::SCPI::IDN] =
        [this](const std::vector<String>& params) { return handleIdentify(params); };
    commandHandlers[Constants::SCPI::MEASURE_QUERY] =
        [this](const std::vector<String>& params) { return handleMeasure(params); };
    commandHandlers[Constants::SCPI::LIST_SENSORS] =
        [this](const std::vector<String>& params) { return handleListSensors(params); };
    commandHandlers[Constants::SCPI::GET_CONFIG] =
        [this](const std::vector<String>& params) { return handleGetConfig(params); };
    commandHandlers[Constants::SCPI::SET_BOARD_ID] =
        [this](const std::vector<String>& params) { return handleSetBoardId(params); };
    commandHandlers[Constants::SCPI::UPDATE_CONFIG] =
        [this](const std::vector<String>& params) { return handleUpdateConfig(params); };
    commandHandlers[Constants::SCPI::UPDATE_SENSOR_CONFIG] =
        [this](const std::vector<String>& params) { return handleUpdateSensorConfig(params); };
    commandHandlers[Constants::SCPI::UPDATE_ADDITIONAL_CONFIG] =
        [this](const std::vector<String>& params) { return handleUpdateAdditionalConfig(params); };
    commandHandlers[Constants::SCPI::TEST_FILESYSTEM] =
        [this](const std::vector<String>& params) { return handleTestFilesystem(params); };
    commandHandlers[Constants::SCPI::TEST_UPDATE] =
        [this](const std::vector<String>& params) { return handleTestUpdateConfig(params); };
    commandHandlers[Constants::SCPI::TEST] =
        [this](const std::vector<String>& params) {
            Serial.println("Serial communication test successful");
            return true;
        };
    commandHandlers[Constants::SCPI::TEST_INFO] =
        [this](const std::vector<String>& params) { return handleTestErrorLevel(params, INFO); };
    commandHandlers[Constants::SCPI::TEST_WARNING] =
        [this](const std::vector<String>& params) { return handleTestErrorLevel(params, WARNING); };
    commandHandlers[Constants::SCPI::TEST_ERROR] =
        [this](const std::vector<String>& params) { return handleTestErrorLevel(params, ERROR); };
    commandHandlers[Constants::SCPI::TEST_FATAL] =
        [this](const std::vector<String>& params) { return handleTestErrorLevel(params, FATAL); };
    commandHandlers[Constants::SCPI::ECHO] =
        [this](const std::vector<String>& params) { return handleEcho(params); };
    commandHandlers[Constants::SCPI::RESET] =
        [this](const std::vector<String>& params) { return handleReset(params); };
    // New simplified message routing commands
    commandHandlers[Constants::SCPI::LOG_STATUS] =
        [this](const std::vector<String>& params) { return handleLogStatus(params); };
    commandHandlers[Constants::SCPI::LOG_ROUTE] =
        [this](const std::vector<String>& params) { return handleLogRouting(params); };
    commandHandlers[Constants::SCPI::LED_IDENTIFY] =
        [this](const std::vector<String>& params) { return handleLedIdentify(params); };
}
References commandHandlers, Constants::SCPI::ECHO, ERROR, FATAL, Constants::SCPI::GET_CONFIG, handleEcho(), handleGetConfig(), handleIdentify(), handleLedIdentify(), handleListSensors(), handleLogRouting(), handleLogStatus(), handleMeasure(), handleReset(), handleSetBoardId(), handleTestErrorLevel(), handleTestFilesystem(), handleTestUpdateConfig(), handleUpdateAdditionalConfig(), handleUpdateConfig(), handleUpdateSensorConfig(), Constants::SCPI::IDN, INFO, Constants::SCPI::LED_IDENTIFY, Constants::SCPI::LIST_SENSORS, Constants::SCPI::LOG_ROUTE, Constants::SCPI::LOG_STATUS, Constants::SCPI::MEASURE_QUERY, Constants::SCPI::RESET, Constants::SCPI::SET_BOARD_ID, Constants::SCPI::TEST, Constants::SCPI::TEST_ERROR, Constants::SCPI::TEST_FATAL, Constants::SCPI::TEST_FILESYSTEM, Constants::SCPI::TEST_INFO, Constants::SCPI::TEST_UPDATE, Constants::SCPI::TEST_WARNING, Constants::SCPI::UPDATE_ADDITIONAL_CONFIG, Constants::SCPI::UPDATE_CONFIG, Constants::SCPI::UPDATE_SENSOR_CONFIG, and WARNING.
Referenced by begin().
setLedManager()
void CommunicationManager::setLedManager (LedManager * led)
Set the LED manager.
Parameters
led Pointer to LED manager
Definition at line 35 of file CommunicationManager.cpp.
{
    ledManager = led;
}
References ledManager.
setUartDebugSerialPtr()
void CommunicationManager::setUartDebugSerialPtr (Print * debugSerial) static
Set the UART debug serial pointer for message routing.
Parameters
debugSerial Pointer to the debug serial
Definition at line 32 of file CommunicationManager.cpp.
{
    uartDebugSerial = debugSerial;
}
References debugSerial, and uartDebugSerial.
Referenced by setUartDebugSerial().
setupCommands()
void CommunicationManager::setupCommands ()
Register all SCPI commands with the parser.
Definition at line 119 of file CommunicationManager.cpp.
{
    REGISTER_COMMAND("*IDN?", handleIdentify)
    REGISTER_COMMAND("MEAS?", handleMeasure)
    REGISTER_COMMAND("SYST:SENS:LIST?", handleListSensors)
    REGISTER_COMMAND("SYST:CONF?", handleGetConfig)
    REGISTER_COMMAND("SYST:CONF:BOARD:ID", handleSetBoardId)
    REGISTER_COMMAND("SYST:CONF:UPDATE", handleUpdateConfig)
    REGISTER_COMMAND("SYST:CONF:SENS:UPDATE", handleUpdateSensorConfig)
    REGISTER_COMMAND("SYST:CONF:ADD:UPDATE", handleUpdateAdditionalConfig)
    REGISTER_COMMAND("TEST", handleEcho)
    REGISTER_COMMAND("TEST:FS", handleTestFilesystem)
    REGISTER_COMMAND("TEST:UPDATE", handleTestUpdateConfig)
    REGISTER_COMMAND("ECHO", handleEcho)
    // New simplified message routing commands
    REGISTER_COMMAND("SYST:LOG?", handleLogStatus)
    REGISTER_COMMAND("SYST:LOG", handleLogRouting)
    REGISTER_COMMAND("SYST:LED:IDENT", handleLedIdentify)
    REGISTER_COMMAND("TEST:INFO", handleTestInfoLevel)
    REGISTER_COMMAND("TEST:WARNING", handleTestWarningLevel)
    REGISTER_COMMAND("TEST:ERROR", handleTestErrorLevel)
    REGISTER_COMMAND("TEST:FATAL", handleTestFatalLevel)
    errorHandler->logError(INFO, "SCPI commands registered");
}
References errorHandler, handleEcho(), handleGetConfig(), handleIdentify(), handleLedIdentify(), handleListSensors(), handleLogRouting(), handleLogStatus(), handleMeasure(), handleSetBoardId(), handleTestErrorLevel(), handleTestFatalLevel(), handleTestFilesystem(), handleTestInfoLevel(), handleTestUpdateConfig(), handleTestWarningLevel(), handleUpdateAdditionalConfig(), handleUpdateConfig(), handleUpdateSensorConfig(), INFO, and REGISTER_COMMAND.
Member Data Documentation
commandHandlers
std::map<String, CommandHandler> CommunicationManager::commandHandlers private
Map of command strings to handler functions.
Definition at line 63 of file CommunicationManager.h.
Referenced by processCommand(), and registerCommandHandlers().
configManager
ConfigManager* CommunicationManager::configManager private
Definition at line 55 of file CommunicationManager.h.
Referenced by CommunicationManager(), getConfigManager(), handleGetConfig(), handleIdentify(), handleSetBoardId(), handleUpdateAdditionalConfig(), handleUpdateConfig(), and handleUpdateSensorConfig().
errorHandler
ErrorHandler* CommunicationManager::errorHandler private
Definition at line 56 of file CommunicationManager.h.
Referenced by begin(), collectSensorReadings(), CommunicationManager(), getErrorHandler(), handleLedIdentify(), handleLogRouting(), handleLogStatus(), handleMeasure(), handleReset(), handleSetBoardId(), handleTestErrorLevel(), handleUpdateAdditionalConfig(), handleUpdateConfig(), handleUpdateSensorConfig(), processCommandLine(), processIncomingData(), and setupCommands().
instance
CommunicationManager * CommunicationManager::instance = nullptr static private
Singleton instance for callback access.
Definition at line 73 of file CommunicationManager.h.
Referenced by CommunicationManager(), and getInstance().
ledManager
LedManager* CommunicationManager::ledManager = nullptr private
Definition at line 57 of file CommunicationManager.h.
Referenced by CommunicationManager(), handleLedIdentify(), handleTestErrorLevel(), and setLedManager().
scpiParser
SCPI_Parser* CommunicationManager::scpiParser private
SCPI parser instance.
Definition at line 48 of file CommunicationManager.h.
Referenced by CommunicationManager(), getScpiParser(), processCommandLine(), processIncomingData(), and ~CommunicationManager().
sensorManager
SensorManager* CommunicationManager::sensorManager private
References to other system managers.
Definition at line 54 of file CommunicationManager.h.
Referenced by collectSensorReadings(), CommunicationManager(), getSensorManager(), handleListSensors(), handleMeasure(), and handleUpdateSensorConfig().
uartDebugSerial
Print * CommunicationManager::uartDebugSerial = nullptr static private
Static reference to UART debug serial.
Definition at line 68 of file CommunicationManager.h.
Referenced by handleLogRouting(), and setUartDebugSerialPtr().
The documentation for this class was generated from the following files:
src/communication/CommunicationManager.h
src/communication/CommunicationManager.cpp