GPower Environmental Monitor: ConfigManager Class Reference
ConfigManager Class Reference
Configuration Management
Manages system configuration and persistence This class handles loading, saving, and modifying the system configuration, including sensors, identification, and general settings.
#include <ConfigManager.h>
Public Member Functions
ConfigManager (ErrorHandler *err)
Constructor.
bool begin ()
Initialize the configuration manager Loads the configuration from file or creates a default one if none exists.
void disableNotifications (bool disable)
Enable or disable notifications Used to prevent recursive notifications during complex configuration updates.
String getBoardIdentifier ()
Board identification methods.
bool setBoardIdentifier (String identifier)
Set the board identifier.
std::vector< SensorConfig > getSensorConfigs ()
Sensor configuration methods.
bool updateSensorConfigs (const std::vector< SensorConfig > &configs)
Update sensor configurations.
String getConfigJson ()
Complete configuration methods.
bool updateConfigFromJson (const String &jsonConfig)
Update configuration from JSON.
bool updateSensorConfigFromJson (const String &jsonConfig)
Granular configuration methods.
bool updateAdditionalConfigFromJson (const String &jsonConfig)
Update only additional configuration.
void registerChangeCallback (ConfigChangeCallback callback)
Change notification.
Private Member Functions
bool loadConfigFromFile ()
Load configuration from file.
bool createDefaultConfig ()
Create default configuration.
void notifyConfigChanged (const String &newConfig)
Notify all registered callbacks about configuration changes.
bool writeConfigToFile (const JsonDocument &doc)
Helper methods for file operations.
bool readConfigFromFile (JsonDocument &doc)
Private Attributes
ErrorHandler * errorHandler
Error handler for logging.
String boardId
Board identifier.
std::vector< SensorConfig > sensorConfigs
Vector of sensor configurations.
String additionalConfig
Additional configuration JSON.
std::vector< ConfigChangeCallback > changeCallbacks
Vector of configuration change callbacks.
bool notifyingCallbacks
Flag to prevent recursive notification.
Detailed Description
Manages system configuration and persistence This class handles loading, saving, and modifying the system configuration, including sensors, identification, and general settings.
It provides a JSON-based interface for configuration updates.
Definition at line 71 of file ConfigManager.h.
Constructor & Destructor Documentation
ConfigManager()
ConfigManager::ConfigManager (ErrorHandler * err)
Constructor.
Parameters
err Pointer to error handler
Definition at line 6 of file ConfigManager.cpp.
                                              : errorHandler(err), notifyingCallbacks(false) {
}
References errorHandler, and notifyingCallbacks.
Member Function Documentation
begin()
bool ConfigManager::begin ()
Initialize the configuration manager Loads the configuration from file or creates a default one if none exists.
Returns
true if initialization succeeded
Definition at line 10 of file ConfigManager.cpp.
{
    return loadConfigFromFile();
}
References loadConfigFromFile().
createDefaultConfig()
bool ConfigManager::createDefaultConfig () private
Create default configuration.
Returns
true if creation succeeded
Definition at line 246 of file ConfigManager.cpp.
{
    const uint32_t DEFAULT_POLLING_RATE = Constants::System::DEFAULT_POLLING_RATE_MS;  // Default: 1 second
    JsonDocument doc;
    // Create default configuration
    doc["Environmental Monitor ID"] = "GPower EM-" + String(ESP.getEfuseMac(), HEX);
    // Add I2C peripherals array and first peripheral
    JsonArray i2cPeripherals = doc["I2C Peripherals"].to<JsonArray>();
    JsonObject i2cPeripheral = i2cPeripherals.add<JsonObject>();
    i2cPeripheral["Peripheral Name"] = "I2C01";
    i2cPeripheral["Peripheral Type"] = "SHT41";
    i2cPeripheral["I2C Port"] = "I2C0";
    i2cPeripheral["Address (HEX)"] = 0x44;  // SHT41 default address
    i2cPeripheral["Polling Rate[1000 ms]"] = DEFAULT_POLLING_RATE;
    i2cPeripheral["Additional"] = "";  // No additional settings by default
    // Add empty SPI peripherals array
    doc["SPI Peripherals"] = JsonArray();
    // Save to file
    File configFile = LittleFS.open(Constants::CONFIG_FILE_PATH, "w");
    if (!configFile) {
        errorHandler->logError(ERROR, "Failed to create config file");
        return false;
    }
    if (serializeJson(doc, configFile) == 0) {
        errorHandler->logError(ERROR, "Failed to write config");
        configFile.close();
        return false;
    }
    configFile.close();
    // Load the configurations we just created
    return loadConfigFromFile();
}
References Constants::CONFIG_FILE_PATH, Constants::System::DEFAULT_POLLING_RATE_MS, ERROR, errorHandler, and loadConfigFromFile().
Referenced by loadConfigFromFile().
disableNotifications()
void ConfigManager::disableNotifications (bool disable)
Enable or disable notifications Used to prevent recursive notifications during complex configuration updates.
Parameters
disable Whether to disable notifications
Definition at line 14 of file ConfigManager.cpp.
{
    notifyingCallbacks = disable;
}
References notifyingCallbacks.
getBoardIdentifier()
String ConfigManager::getBoardIdentifier ()
Board identification methods.
Get the board identifier
Returns
The board's unique identifier
Definition at line 287 of file ConfigManager.cpp.
{
    return boardId;
}
References boardId.
getConfigJson()
String ConfigManager::getConfigJson ()
Complete configuration methods.
Get complete configuration as JSON
Returns
Configuration JSON string
Definition at line 425 of file ConfigManager.cpp.
{
    if (!LittleFS.exists(Constants::CONFIG_FILE_PATH)) {
        errorHandler->logError(WARNING, "Config file not found for retrieval");
        return "{}";
    }
    File configFile = LittleFS.open(Constants::CONFIG_FILE_PATH, "r");
    if (!configFile) {
        errorHandler->logError(ERROR, "Failed to open config file for retrieval");
        return "{}";
    }
    String configStr = configFile.readString();
    configFile.close();
    return configStr;
}
References Constants::CONFIG_FILE_PATH, ERROR, errorHandler, and WARNING.
Referenced by updateConfigFromJson().
getSensorConfigs()
std::vector< SensorConfig > ConfigManager::getSensorConfigs ()
Sensor configuration methods.
Get all sensor configurations
Returns
Vector of sensor configurations
Definition at line 340 of file ConfigManager.cpp.
{
    return sensorConfigs;
}
References sensorConfigs.
loadConfigFromFile()
bool ConfigManager::loadConfigFromFile () private
Load configuration from file.
Returns
true if loading succeeded
Definition at line 47 of file ConfigManager.cpp.
{
    errorHandler->logError(INFO, "Loading config file");
    // Define polling rate constraints
    const uint32_t DEFAULT_POLLING_RATE = Constants::System::DEFAULT_POLLING_RATE_MS;
    const uint32_t MIN_POLLING_RATE = Constants::System::MIN_POLLING_RATE_MS;
    const uint32_t MAX_POLLING_RATE = Constants::System::MAX_POLLING_RATE_MS;
    // Check if config file exists
    if (!LittleFS.exists(Constants::CONFIG_FILE_PATH)) {
        errorHandler->logError(WARNING, "Config file not found, creating default");
        if (!createDefaultConfig()) {
            errorHandler->logError(ERROR, "Failed to create default config");
            return false;
        }
    }
    // Open and read config file
    errorHandler->logError(INFO, "Opening config file for reading");
    File configFile = LittleFS.open(Constants::CONFIG_FILE_PATH, "r");
    if (!configFile) {
        errorHandler->logError(ERROR, "Failed to open config file");
        return false;
    }
    // Parse JSON
    JsonDocument doc;
    DeserializationError error = deserializeJson(doc, configFile);
    configFile.close();
    if (error) {
        errorHandler->logError(ERROR, "Failed to parse config: " + String(error.c_str()));
        return false;
    }
    // Check if deserialization exceeded memory limits
    if (doc.overflowed()) {
        errorHandler->logError(ERROR, "Config too large for available memory");
        return false;
    }
    errorHandler->logError(INFO, "JSON parsed successfully");
    // Extract Environmental Monitor IDentifier - handle both old and new key names for backward compatibility
    if (doc["Environmental Monitor ID"].is<String>()) {
        boardId = doc["Environmental Monitor ID"].as<String>();
        errorHandler->logError(INFO, "Using Environmental Monitor ID: " + boardId);
    } else {
        boardId = "GPower EM-" + String(ESP.getEfuseMac(), HEX);
        errorHandler->logError(INFO, "No ID found, using default: " + boardId);
    }
    // Clear existing configurations
    sensorConfigs.clear();
    additionalConfig = "";
    errorHandler->logError(INFO, "Cleared existing configurations");
    // Load I2C peripherals - using the "Peripheral" naming in JSON but "sensor" internally
    JsonArray i2cPeripherals = doc["I2C Peripherals"].as<JsonArray>();
    errorHandler->logError(INFO, "I2C Peripherals array exists: " + String(i2cPeripherals.size() > 0 ? "YES" : "NO"));
    if (i2cPeripherals.size() > 0) {
        errorHandler->logError(INFO, "Found " + String(i2cPeripherals.size()) + " I2C peripherals");
        for (JsonObject peripheral : i2cPeripherals) {
            if (!peripheral["Peripheral Name"].is<String>() || !peripheral["Peripheral Type"].is<String>() ||
                !peripheral["Address (HEX)"].is<int>()) {
                errorHandler->logError(WARNING, "Skipping I2C peripheral with missing required fields");
                continue;
            }
            SensorConfig config;
            config.name = peripheral["Peripheral Name"].as<String>();
            config.type = peripheral["Peripheral Type"].as<String>();
            config.address = peripheral["Address (HEX)"].as<int>();
            config.isSPI = false;
            errorHandler->logError(INFO, "Found I2C peripheral: " + config.name + " of type " + config.type);
            // Handle I2C port (new field)
            if (peripheral["I2C Port"].is<String>()) {
                String portStr = peripheral["I2C Port"].as<String>();
                config.i2cPort = I2CManager::stringToPort(portStr);
                errorHandler->logError(INFO, "Peripheral using I2C port " + portStr);
            } else {
                // Default to I2C0 if not specified
                config.i2cPort = I2CPort::I2C0;
                errorHandler->logError(INFO, "Peripheral defaulting to I2C0 (no port specified)");
            }
            // Read and validate polling rate
            if (peripheral["Polling Rate[1000 ms]"].is<uint32_t>()) {
                uint32_t rate = peripheral["Polling Rate[1000 ms]"].as<uint32_t>();
                // Apply validation rules
                if (rate < MIN_POLLING_RATE) {
                    errorHandler->logError(WARNING, "Polling rate too low for peripheral " + config.name +
                                             " (" + String(rate) + "ms), using " +
                                             String(MIN_POLLING_RATE) + "ms minimum");
                    config.pollingRate = MIN_POLLING_RATE;
                } else if (rate > MAX_POLLING_RATE) {
                    errorHandler->logError(WARNING, "Polling rate too high for peripheral " + config.name +
                                             " (" + String(rate) + "ms), using " +
                                             String(MAX_POLLING_RATE) + "ms maximum");
                    config.pollingRate = MAX_POLLING_RATE;
                } else {
                    config.pollingRate = rate;
                }
                errorHandler->logError(INFO, "Peripheral polling rate: " + String(config.pollingRate) + "ms");
            } else {
                config.pollingRate = DEFAULT_POLLING_RATE;
                errorHandler->logError(INFO, "Using default polling rate: " + String(DEFAULT_POLLING_RATE) + "ms");
            }
            // Read additional settings
            if (peripheral["Additional"].is<String>()) {
                config.additional = peripheral["Additional"].as<String>();
                errorHandler->logError(INFO, "Additional settings: " + config.additional);
            } else {
                config.additional = ""; // Empty string for no additional settings
            }
            sensorConfigs.push_back(config);
            errorHandler->logError(INFO, "Added I2C peripheral: " + config.name);
        }
    }
    // Load SPI peripherals - using the "Peripheral" naming in JSON but "sensor" internally
    JsonArray spiPeripherals = doc["SPI Peripherals"].as<JsonArray>();
    errorHandler->logError(INFO, "SPI Peripherals array exists: " + String(spiPeripherals.size() > 0 ? "YES" : "NO"));
    if (spiPeripherals.size() > 0) {
        errorHandler->logError(INFO, "Found " + String(spiPeripherals.size()) + " SPI peripherals");
        for (JsonObject peripheral : spiPeripherals) {
            if (!peripheral["Peripheral Name"].is<String>() || !peripheral["Peripheral Type"].is<String>() ||
                !peripheral["SS Pin"].is<int>()) {
                errorHandler->logError(WARNING, "Skipping SPI peripheral with missing required fields");
                continue;
            }
            SensorConfig config;
            config.name = peripheral["Peripheral Name"].as<String>();
            config.type = peripheral["Peripheral Type"].as<String>();
            config.address = peripheral["SS Pin"].as<int>();
            config.isSPI = true;
            errorHandler->logError(INFO, "Found SPI peripheral: " + config.name + " of type " + config.type);
            // SPI peripherals don't use I2C port
            config.i2cPort = I2CPort::I2C0; // Default value, not used
            // Read and validate polling rate
            if (peripheral["Polling Rate[1000 ms]"].is<uint32_t>()) {
                uint32_t rate = peripheral["Polling Rate[1000 ms]"].as<uint32_t>();
                // Apply validation rules
                if (rate < MIN_POLLING_RATE) {
                    errorHandler->logError(WARNING, "Polling rate too low for peripheral " + config.name +
                                             " (" + String(rate) + "ms), using " +
                                             String(MIN_POLLING_RATE) + "ms minimum");
                    config.pollingRate = MIN_POLLING_RATE;
                } else if (rate > MAX_POLLING_RATE) {
                    errorHandler->logError(WARNING, "Polling rate too high for peripheral " + config.name +
                                             " (" + String(rate) + "ms), using " +
                                             String(MAX_POLLING_RATE) + "ms maximum");
                    config.pollingRate = MAX_POLLING_RATE;
                } else {
                    config.pollingRate = rate;
                }
                errorHandler->logError(INFO, "Peripheral polling rate: " + String(config.pollingRate) + "ms");
            } else {
                config.pollingRate = DEFAULT_POLLING_RATE;
                errorHandler->logError(INFO, "Using default polling rate: " + String(DEFAULT_POLLING_RATE) + "ms");
            }
            // Read additional settings
            if (peripheral["Additional"].is<String>()) {
                config.additional = peripheral["Additional"].as<String>();
                errorHandler->logError(INFO, "Additional settings: " + config.additional);
            } else {
                config.additional = ""; // Empty string for no additional settings
            }
            sensorConfigs.push_back(config);
            errorHandler->logError(INFO, "Added SPI peripheral: " + config.name);
        }
    }
    // Load Additional configuration if present
    if (doc["Additional"].is<JsonObject>()) {
        // Serialize the Additional field to a string
        String additionalJson;
        serializeJson(doc["Additional"], additionalJson);
        additionalConfig = additionalJson;
        errorHandler->logError(INFO, "Loaded additional configuration section");
    }
    errorHandler->logError(INFO, "Configuration loaded successfully with " + String(sensorConfigs.size()) + " peripherals");
    return true;
}
References SensorConfig::additional, additionalConfig, SensorConfig::address, boardId, Constants::CONFIG_FILE_PATH, createDefaultConfig(), Constants::System::DEFAULT_POLLING_RATE_MS, ERROR, errorHandler, I2C0, SensorConfig::i2cPort, INFO, SensorConfig::isSPI, Constants::System::MAX_POLLING_RATE_MS, Constants::System::MIN_POLLING_RATE_MS, SensorConfig::name, SensorConfig::pollingRate, sensorConfigs, I2CManager::stringToPort(), SensorConfig::type, and WARNING.
Referenced by begin(), createDefaultConfig(), and updateConfigFromJson().
notifyConfigChanged()
void ConfigManager::notifyConfigChanged (const String & newConfig) private
Notify all registered callbacks about configuration changes.
Parameters
newConfig The new configuration JSON
Definition at line 27 of file ConfigManager.cpp.
{
    // Prevent recursive notifications
    if (notifyingCallbacks) {
        errorHandler->logError(INFO, "Preventing recursive notification of config changes");
        return;
    }
    notifyingCallbacks = true;
    errorHandler->logError(INFO, "Notifying " + String(changeCallbacks.size()) + " callbacks about config change");
    for (auto callback : changeCallbacks) {
        errorHandler->logError(INFO, "Calling a callback...");
        callback(newConfig);
    }
    notifyingCallbacks = false;
    errorHandler->logError(INFO, "All callbacks notified");
}
References changeCallbacks, errorHandler, INFO, and notifyingCallbacks.
Referenced by setBoardIdentifier(), updateAdditionalConfigFromJson(), updateConfigFromJson(), updateSensorConfigFromJson(), and updateSensorConfigs().
readConfigFromFile()
bool ConfigManager::readConfigFromFile (JsonDocument & doc) private
Definition at line 520 of file ConfigManager.cpp.
{
    if (!LittleFS.exists(Constants::CONFIG_FILE_PATH)) {
        errorHandler->logError(ERROR, "Config file not found");
        return false;
    }
    File configFile = LittleFS.open(Constants::CONFIG_FILE_PATH, "r");
    if (!configFile) {
        errorHandler->logError(ERROR, "Failed to open config file for reading");
        return false;
    }
    DeserializationError error = deserializeJson(doc, configFile);
    configFile.close();
    if (error) {
        errorHandler->logError(ERROR, "Failed to parse config file: " + String(error.c_str()));
        return false;
    }
    return true;
}
References Constants::CONFIG_FILE_PATH, ERROR, and errorHandler.
Referenced by updateAdditionalConfigFromJson(), and updateSensorConfigFromJson().
registerChangeCallback()
void ConfigManager::registerChangeCallback (ConfigChangeCallback callback)
Change notification.
Register callback for configuration changes
Parameters
callback Function to call when configuration changes
Definition at line 19 of file ConfigManager.cpp.
{
    if (callback) {
        changeCallbacks.push_back(callback);
        errorHandler->logError(INFO, "Registered config change callback, total callbacks: " + String(changeCallbacks.size()));
    }
}
References changeCallbacks, errorHandler, and INFO.
setBoardIdentifier()
bool ConfigManager::setBoardIdentifier (String identifier)
Set the board identifier.
Parameters
identifier The new identifier
Returns
true if update succeeded
Definition at line 292 of file ConfigManager.cpp.
{
    // Update Environmental Monitor ID in memory
    boardId = identifier;
    // Update config file
    File configFile = LittleFS.open(Constants::CONFIG_FILE_PATH, "r");
    if (!configFile) {
        errorHandler->logError(ERROR, "Failed to open config file for reading");
        return false;
    }
    JsonDocument doc;
    DeserializationError error = deserializeJson(doc, configFile);
    configFile.close();
    if (error) {
        errorHandler->logError(ERROR, "Failed to parse config when updating Environmental Monitor ID");
        return false;
    }
    // Update the Environmental Monitor ID in the JSON document
    doc["Environmental Monitor ID"] = boardId;
    // Save the updated configuration
    configFile = LittleFS.open(Constants::CONFIG_FILE_PATH, "w");
    if (!configFile) {
        errorHandler->logError(ERROR, "Failed to open config file for writing");
        return false;
    }
    if (serializeJson(doc, configFile) == 0) {
        errorHandler->logError(ERROR, "Failed to write updated config");
        configFile.close();
        return false;
    }
    configFile.close();
    errorHandler->logError(INFO, "Updated Environmental Monitor ID to: " + boardId);
    // Notify about the configuration change
    String configJson;
    serializeJson(doc, configJson);
    notifyConfigChanged(configJson);
    return true;
}
References boardId, Constants::CONFIG_FILE_PATH, ERROR, errorHandler, INFO, and notifyConfigChanged().
updateAdditionalConfigFromJson()
bool ConfigManager::updateAdditionalConfigFromJson (const String & jsonConfig)
Update only additional configuration.
Parameters
jsonConfig Additional configuration JSON
Returns
true if update succeeded
Definition at line 707 of file ConfigManager.cpp.
{
    // Handle empty input - erase additional config with warning
    if (jsonConfig.length() == 0 || jsonConfig == "{}" || jsonConfig == "null") {
        errorHandler->logError(WARNING, "Empty additional configuration received - clearing additional section");
        additionalConfig = "";
        // Update the configuration file
        JsonDocument doc;
        if (!readConfigFromFile(doc)) {
            errorHandler->logError(ERROR, "Failed to read existing configuration");
            return false;
        }
        // Remove Additional field if it exists
        if (doc["Additional"].is<JsonObject>()) {
            doc.remove("Additional");
        }
        // Write updated configuration to file
        return writeConfigToFile(doc);
    }
    // Clean the input JSON and parse it
    String cleanJson = jsonConfig;
    int jsonStart = cleanJson.indexOf('{');
    if (jsonStart > 0) {
        cleanJson = cleanJson.substring(jsonStart);
    }
    JsonDocument doc;
    DeserializationError error = deserializeJson(doc, cleanJson);
    if (error || doc.overflowed()) {
        errorHandler->logError(ERROR, "Failed to parse additional configuration JSON: " +
                              (error ? String(error.c_str()) : "Document too large"));
        return false;
    }
    // Extract Additional configuration if present
    String newAdditionalConfig = "";
    if (doc["Additional"].is<JsonObject>()) {
        // Serialize the Additional field to a string if it's an object
        serializeJson(doc["Additional"], newAdditionalConfig);
    } else if (doc["Additional"].is<String>()) {
        // Use the string directly if it's a string
        newAdditionalConfig = doc["Additional"].as<String>();
    } else {
        // Convert to string if it's another type
        newAdditionalConfig = doc["Additional"].as<String>();
    }
    // Backup existing additional config
    String oldAdditionalConfig = additionalConfig;
    // Update additional config
    additionalConfig = newAdditionalConfig;
    // Read current configuration file to get other parts
    JsonDocument fullDoc;
    if (!readConfigFromFile(fullDoc)) {
        // Failed to read existing config, revert to old additional config
        additionalConfig = oldAdditionalConfig;
        return false;
    }
    // Update the Additional field
    if (additionalConfig.length() > 0) {
        // Parse the additionalConfig to a JSON object
        JsonDocument additionalDoc;
        DeserializationError additionalError = deserializeJson(additionalDoc, additionalConfig);
    if (!additionalError && !additionalConfig.startsWith("\"")) {
        // If it's a valid JSON object and not a JSON string, store as object
        fullDoc["Additional"] = additionalDoc;
    } else {
        // If not a valid JSON object or it's a JSON string, store as raw string
        fullDoc["Additional"] = additionalConfig;
    }
    }
    // Write updated configuration to file
    if (!writeConfigToFile(fullDoc)) {
        // If writing fails, revert to old configuration
        additionalConfig = oldAdditionalConfig;
        errorHandler->logError(ERROR, "Failed to write updated additional configuration");
        return false;
    }
    errorHandler->logError(INFO, "Additional configuration updated successfully");
    // Notify about the configuration change
    String configJson;
    serializeJson(fullDoc, configJson);
    notifyConfigChanged(configJson);
    return true;
}
References additionalConfig, ERROR, errorHandler, INFO, notifyConfigChanged(), readConfigFromFile(), WARNING, and writeConfigToFile().
updateConfigFromJson()
bool ConfigManager::updateConfigFromJson (const String & jsonConfig)
Update configuration from JSON.
Parameters
jsonConfig Complete configuration JSON
Returns
true if update succeeded
Definition at line 444 of file ConfigManager.cpp.
{
    // Log a shorter version of the config to avoid huge logs
    errorHandler->logError(INFO, "Received config update: " +
                         jsonConfig.substring(0, std::min(50, (int)jsonConfig.length())) +
                         (jsonConfig.length() > 50 ? "..." : ""));
    // Make a backup of the current configuration
    String backupConfig = getConfigJson();
    // Extract clean JSON data by finding the opening brace
    int jsonStart = jsonConfig.indexOf('{');
    if (jsonStart < 0) {
        errorHandler->logError(ERROR, "No JSON object found in config");
        return false;
    }
    String cleanJson = jsonConfig.substring(jsonStart);
    // Parse the JSON
    JsonDocument doc;
    DeserializationError error = deserializeJson(doc, cleanJson);
    if (error || doc.overflowed()) {
        errorHandler->logError(ERROR, "Failed to parse JSON config: " +
                              (error ? String(error.c_str()) : "Document too large"));
        return false;
    }
    // Save to file
    if (!writeConfigToFile(doc)) {
        errorHandler->logError(ERROR, "Failed to write new configuration to file");
        return false;
    }
    // Reload and notify
    bool success = loadConfigFromFile();
    if (success) {
        errorHandler->logError(INFO, "Config reloaded successfully, notifying listeners");
        notifyConfigChanged(jsonConfig);
    } else {
        errorHandler->logError(ERROR, "Failed to reload configuration, rolling back to previous state");
        // Restore the previous configuration
        JsonDocument backupDoc;
        DeserializationError backupError = deserializeJson(backupDoc, backupConfig);
        if (!backupError && writeConfigToFile(backupDoc)) {
            errorHandler->logError(INFO, "Successfully rolled back to previous configuration");
            loadConfigFromFile(); // Reload the backup configuration
        } else {
            errorHandler->logError(ERROR, "Failed to roll back to previous configuration");
        }
    }
    return success;
}
References ERROR, errorHandler, getConfigJson(), INFO, loadConfigFromFile(), notifyConfigChanged(), and writeConfigToFile().
updateSensorConfigFromJson()
bool ConfigManager::updateSensorConfigFromJson (const String & jsonConfig)
Granular configuration methods.
Update only sensor configuration from JSON
Parameters
jsonConfig Sensor configuration JSON
Returns
true if update succeeded
Definition at line 544 of file ConfigManager.cpp.
{
    // Handle empty input - erase peripherals with warning
    if (jsonConfig.length() == 0 || jsonConfig == "{}" || jsonConfig == "null") {
        errorHandler->logError(WARNING, "Empty peripheral configuration received - clearing all peripherals");
        sensorConfigs.clear();
        // Update the configuration file
        return updateSensorConfigs(sensorConfigs);
    }
    // Clean the input JSON and parse it
    String cleanJson = jsonConfig;
    int jsonStart = cleanJson.indexOf('{');
    if (jsonStart > 0) {
        cleanJson = cleanJson.substring(jsonStart);
    }
    JsonDocument doc;
    DeserializationError error = deserializeJson(doc, cleanJson);
    if (error || doc.overflowed()) {
        errorHandler->logError(ERROR, "Failed to parse peripheral configuration JSON: " +
                              (error ? String(error.c_str()) : "Document too large"));
        return false;
    }
    // Temporary storage for new configurations
    std::vector<SensorConfig> newSensorConfigs;
    // Extract I2C peripherals if present
    if (doc["I2C Peripherals"].is<JsonArray>()) {
        JsonArray i2cPeripherals = doc["I2C Peripherals"].as<JsonArray>();
        for (JsonObject peripheral : i2cPeripherals) {
            if (!peripheral["Peripheral Name"].is<String>() || !peripheral["Peripheral Type"].is<String>() ||
                !peripheral["Address (HEX)"].is<int>()) {
                errorHandler->logError(ERROR, "Missing required fields in I2C peripheral configuration");
                continue;
            }
            SensorConfig config;
            config.name = peripheral["Peripheral Name"].as<String>();
            config.type = peripheral["Peripheral Type"].as<String>();
            config.address = peripheral["Address (HEX)"].as<int>();
            config.isSPI = false;
            // Optional fields with defaults
            config.i2cPort = I2CManager::stringToPort(
                peripheral["I2C Port"].is<String>() ? peripheral["I2C Port"].as<String>() : "I2C0");
            config.pollingRate = peripheral["Polling Rate[1000 ms]"].is<uint32_t>() ?
                peripheral["Polling Rate[1000 ms]"].as<uint32_t>() : 1000;
            config.additional = peripheral["Additional"].is<String>() ?
                peripheral["Additional"].as<String>() : "";
            // Apply polling rate limits
            config.pollingRate = constrain(config.pollingRate, 50, 300000);
            newSensorConfigs.push_back(config);
        }
    }
    // Extract SPI peripherals if present
    if (doc["SPI Peripherals"].is<JsonArray>()) {
        JsonArray spiPeripherals = doc["SPI Peripherals"].as<JsonArray>();
        for (JsonObject peripheral : spiPeripherals) {
            if (!peripheral["Peripheral Name"].is<String>() || !peripheral["Peripheral Type"].is<String>() ||
                !peripheral["SS Pin"].is<int>()) {
                errorHandler->logError(ERROR, "Missing required fields in SPI peripheral configuration");
                continue;
            }
            SensorConfig config;
            config.name = peripheral["Peripheral Name"].as<String>();
            config.type = peripheral["Peripheral Type"].as<String>();
            config.address = peripheral["SS Pin"].as<int>();
            config.isSPI = true;
            // Optional fields with defaults
            config.pollingRate = peripheral["Polling Rate[1000 ms]"].is<uint32_t>() ?
                peripheral["Polling Rate[1000 ms]"].as<uint32_t>() : 1000;
            config.additional = peripheral["Additional"].is<String>() ?
                peripheral["Additional"].as<String>() : "";
            // Apply polling rate limits
            config.pollingRate = constrain(config.pollingRate, 50, 300000);
            newSensorConfigs.push_back(config);
        }
    }
    // Verify we have at least one valid peripheral if we received config
    if (newSensorConfigs.empty() &&
        (doc["I2C Peripherals"].is<JsonArray>() || doc["SPI Peripherals"].is<JsonArray>())) {
        errorHandler->logError(WARNING, "No valid peripherals found in configuration, keeping existing peripherals");
        return false;
    }
    // Backup existing config before updating
    std::vector<SensorConfig> oldSensorConfigs = sensorConfigs;
    // Update peripheral configs
    sensorConfigs = newSensorConfigs;
    // Read current configuration file to get non-peripheral parts
    JsonDocument fullDoc;
    if (!readConfigFromFile(fullDoc)) {
        // Failed to read existing config, revert to old peripherals
        sensorConfigs = oldSensorConfigs;
        return false;
    }
    // Clear existing peripheral arrays
    fullDoc["I2C Peripherals"] = JsonArray();
    fullDoc["SPI Peripherals"] = JsonArray();
    // Add updated peripherals
    JsonArray i2cPeripherals = fullDoc["I2C Peripherals"].to<JsonArray>();
    JsonArray spiPeripherals = fullDoc["SPI Peripherals"].to<JsonArray>();
    for (const auto& config : sensorConfigs) {
        if (config.isSPI) {
            JsonObject peripheral = spiPeripherals.add<JsonObject>();
            peripheral["Peripheral Name"] = config.name;
            peripheral["Peripheral Type"] = config.type;
            peripheral["SS Pin"] = config.address;
            peripheral["Polling Rate[1000 ms]"] = config.pollingRate;
            if (config.additional.length() > 0) {
                peripheral["Additional"] = config.additional;
            }
        } else {
            JsonObject peripheral = i2cPeripherals.add<JsonObject>();
            peripheral["Peripheral Name"] = config.name;
            peripheral["Peripheral Type"] = config.type;
            peripheral["I2C Port"] = I2CManager::portToString(config.i2cPort);
            peripheral["Address (HEX)"] = config.address;
            peripheral["Polling Rate[1000 ms]"] = config.pollingRate;
            if (config.additional.length() > 0) {
                peripheral["Additional"] = config.additional;
            }
        }
    }
    // Write updated configuration to file
    if (!writeConfigToFile(fullDoc)) {
        // If writing fails, revert to old configuration
        sensorConfigs = oldSensorConfigs;
        errorHandler->logError(ERROR, "Failed to write updated peripheral configuration");
        return false;
    }
    errorHandler->logError(INFO, "Peripheral configuration updated successfully with " +
                       String(sensorConfigs.size()) + " peripherals");
    // Notify about the configuration change
    String configJson;
    serializeJson(fullDoc, configJson);
    notifyConfigChanged(configJson);
    return true;
}
References SensorConfig::additional, SensorConfig::address, ERROR, errorHandler, SensorConfig::i2cPort, INFO, SensorConfig::isSPI, SensorConfig::name, notifyConfigChanged(), SensorConfig::pollingRate, I2CManager::portToString(), readConfigFromFile(), sensorConfigs, I2CManager::stringToPort(), SensorConfig::type, updateSensorConfigs(), WARNING, and writeConfigToFile().
updateSensorConfigs()
bool ConfigManager::updateSensorConfigs (const std::vector< SensorConfig > & configs)
Update sensor configurations.
Parameters
configs Vector of new sensor configurations
Returns
true if update succeeded
Definition at line 345 of file ConfigManager.cpp.
{
    // Update memory copy
    sensorConfigs = configs;
    // Load existing config
    File configFile = LittleFS.open(Constants::CONFIG_FILE_PATH, "r");
    if (!configFile) {
        errorHandler->logError(ERROR, "Failed to open config file for reading");
        return false;
    }
    JsonDocument doc;
    DeserializationError error = deserializeJson(doc, configFile);
    configFile.close();
    if (error) {
        errorHandler->logError(ERROR, "Failed to parse config when updating peripherals");
        return false;
    }
    // Clear existing peripherals
    doc["I2C Peripherals"] = JsonArray();
    doc["SPI Peripherals"] = JsonArray();
    // Add updated peripherals
    JsonArray i2cPeripherals = doc["I2C Peripherals"].to<JsonArray>();
    JsonArray spiPeripherals = doc["SPI Peripherals"].to<JsonArray>();
    for (const auto& config : configs) {
        if (config.isSPI) {
            JsonObject peripheral = spiPeripherals.add<JsonObject>();
            peripheral["Peripheral Name"] = config.name;
            peripheral["Peripheral Type"] = config.type;
            peripheral["SS Pin"] = config.address;
            peripheral["Polling Rate[1000 ms]"] = config.pollingRate;
            // Add the additional field
            if (config.additional.length() > 0) {
                peripheral["Additional"] = config.additional;
            }
        } else {
            JsonObject peripheral = i2cPeripherals.add<JsonObject>();
            peripheral["Peripheral Name"] = config.name;
            peripheral["Peripheral Type"] = config.type;
            peripheral["I2C Port"] = I2CManager::portToString(config.i2cPort);
            peripheral["Address (HEX)"] = config.address;
            peripheral["Polling Rate[1000 ms]"] = config.pollingRate;
            // Add the additional field
            if (config.additional.length() > 0) {
                peripheral["Additional"] = config.additional;
            }
        }
    }
    // Save the updated configuration
    configFile = LittleFS.open(Constants::CONFIG_FILE_PATH, "w");
    if (!configFile) {
        errorHandler->logError(ERROR, "Failed to open config file for writing");
        return false;
    }
    if (serializeJson(doc, configFile) == 0) {
        errorHandler->logError(ERROR, "Failed to write updated config");
        configFile.close();
        return false;
    }
    configFile.close();
    errorHandler->logError(INFO, "Updated peripheral configurations");
    // Notify about the configuration change, but only if we're not already in a notification
    if (!notifyingCallbacks) {
        String configJson;
        serializeJson(doc, configJson);
        notifyConfigChanged(configJson);
    }
    return true;
}
References Constants::CONFIG_FILE_PATH, ERROR, errorHandler, INFO, notifyConfigChanged(), notifyingCallbacks, I2CManager::portToString(), and sensorConfigs.
Referenced by updateSensorConfigFromJson().
writeConfigToFile()
bool ConfigManager::writeConfigToFile (const JsonDocument & doc) private
Helper methods for file operations.
Definition at line 501 of file ConfigManager.cpp.
{
    File configFile = LittleFS.open(Constants::CONFIG_FILE_PATH, "w");
    if (!configFile) {
        errorHandler->logError(ERROR, "Failed to open config file for writing");
        return false;
    }
    size_t written = serializeJson(doc, configFile);
    configFile.close();
    if (written == 0) {
        errorHandler->logError(ERROR, "Failed to write config - 0 bytes written");
        return false;
    }
    return true;
}
References Constants::CONFIG_FILE_PATH, ERROR, and errorHandler.
Referenced by updateAdditionalConfigFromJson(), updateConfigFromJson(), and updateSensorConfigFromJson().
Member Data Documentation
additionalConfig
String ConfigManager::additionalConfig private
Additional configuration JSON.
Definition at line 91 of file ConfigManager.h.
Referenced by loadConfigFromFile(), and updateAdditionalConfigFromJson().
boardId
String ConfigManager::boardId private
Board identifier.
Definition at line 81 of file ConfigManager.h.
Referenced by getBoardIdentifier(), loadConfigFromFile(), and setBoardIdentifier().
changeCallbacks
std::vector<ConfigChangeCallback> ConfigManager::changeCallbacks private
Vector of configuration change callbacks.
Definition at line 96 of file ConfigManager.h.
Referenced by notifyConfigChanged(), and registerChangeCallback().
errorHandler
ErrorHandler* ConfigManager::errorHandler private
Error handler for logging.
Definition at line 76 of file ConfigManager.h.
Referenced by ConfigManager(), createDefaultConfig(), getConfigJson(), loadConfigFromFile(), notifyConfigChanged(), readConfigFromFile(), registerChangeCallback(), setBoardIdentifier(), updateAdditionalConfigFromJson(), updateConfigFromJson(), updateSensorConfigFromJson(), updateSensorConfigs(), and writeConfigToFile().
notifyingCallbacks
bool ConfigManager::notifyingCallbacks private
Flag to prevent recursive notification.
Definition at line 101 of file ConfigManager.h.
Referenced by ConfigManager(), disableNotifications(), notifyConfigChanged(), and updateSensorConfigs().
sensorConfigs
std::vector<SensorConfig> ConfigManager::sensorConfigs private
Vector of sensor configurations.
Definition at line 86 of file ConfigManager.h.
Referenced by getSensorConfigs(), loadConfigFromFile(), updateSensorConfigFromJson(), and updateSensorConfigs().
The documentation for this class was generated from the following files:
src/config/ConfigManager.h
src/config/ConfigManager.cpp