GPower Environmental Monitor: Si7021Sensor Class Reference
Si7021Sensor Class Reference
Implementation of the Si7021 temperature and humidity sensor.
#include <Si7021Sensor.h>
Public Member Functions
Si7021Sensor (const String &sensorName, int address, TwoWire *i2cBus, I2CManager *i2cMgr, I2CPort port, ErrorHandler *err)
Constructor for Si7021Sensor.
~Si7021Sensor ()
Destructor.
bool initialize () override
Initialize the sensor hardware.
float readTemperature () override
Read the current temperature value from the sensor.
float readHumidity () override
Read the current humidity value from the sensor.
unsigned long getTemperatureTimestamp () const override
Get the timestamp of the last temperature reading.
unsigned long getHumidityTimestamp () const override
Get the timestamp of the last humidity reading.
bool performSelfTest () override
Perform a self-test to verify the sensor is functioning properly.
String getSensorInfo () const override
Get detailed information about the sensor.
bool supportsInterface (InterfaceType type) const override
Check if this sensor supports a specific interface.
void * getInterface (InterfaceType type) const override
Get the interface implementation for a specific type.
bool reinitialize ()
Re-initialize the sensor after a communication failure.
Public Member Functions inherited from BaseSensor
BaseSensor (const String &sensorName, SensorType sensorType, ErrorHandler *err)
Constructor for BaseSensor.
virtual ~BaseSensor ()
Virtual destructor.
String getName () const override
Get the name of the sensor.
bool isConnected () const override
Check if the sensor is currently connected and operational.
SensorType getType () const
Get the type of this sensor as an enum value.
String getTypeString () const override
Get the type of this sensor as a string.
Public Member Functions inherited from ISensor
virtual ~ISensor ()=default
Virtual destructor.
Public Member Functions inherited from ITemperatureSensor
virtual ~ITemperatureSensor ()=default
Virtual destructor.
Public Member Functions inherited from IHumiditySensor
virtual ~IHumiditySensor ()=default
Virtual destructor.
Private Member Functions
bool updateReadings () const
Update both temperature and humidity readings from the sensor.
Private Attributes
Adafruit_Si7021 si7021
Underlying Adafruit driver (mutable for const methods)
TwoWire * wire
I2C bus for communication.
I2CPort i2cPort
I2C port identifier.
I2CManager * i2cManager
Reference to I2C manager.
int i2cAddress
I2C address of the sensor.
float lastTemperature
Last temperature reading.
float lastHumidity
Last humidity reading.
unsigned long tempTimestamp
Timestamp of last temperature reading.
unsigned long humTimestamp
Timestamp of last humidity reading.
Additional Inherited Members
Protected Attributes inherited from BaseSensor
String name
Unique identifier for this sensor.
SensorType type
Type of sensor.
bool connected
Connection status.
ErrorHandler * errorHandler
Error reporting mechanism.
Detailed Description
Implementation of the Si7021 temperature and humidity sensor.
This class provides access to the Si7021 sensor, which can measure both temperature and humidity.
Definition at line 17 of file Si7021Sensor.h.
Constructor & Destructor Documentation
Si7021Sensor()
Si7021Sensor::Si7021Sensor (const String & sensorName, int address, TwoWire * i2cBus, I2CManager * i2cMgr, I2CPort port, ErrorHandler * err)
Constructor for Si7021Sensor.
Parameters
sensorName Name/identifier for this sensor instance.
address I2C address of the sensor.
i2cBus The I2C bus to use.
i2cMgr Reference to the I2C manager.
port The I2C port identifier.
err Pointer to the error handler for logging.
Definition at line 3 of file Si7021Sensor.cpp.
    : BaseSensor(sensorName, SensorType::SI7021, err),
      si7021(i2cBus), // Pass wire directly to the constructor
      wire(i2cBus),
      i2cPort(port),
      i2cManager(i2cMgr),
      i2cAddress(address),
      lastTemperature(NAN),
      lastHumidity(NAN),
      tempTimestamp(0),
      humTimestamp(0) {
}
References BaseSensor::BaseSensor(), humTimestamp, i2cAddress, i2cManager, i2cPort, lastHumidity, lastTemperature, SI7021, si7021, tempTimestamp, and wire.
Referenced by updateReadings().
~Si7021Sensor()
Si7021Sensor::~Si7021Sensor ()
Destructor.
Definition at line 17 of file Si7021Sensor.cpp.
{
    // Nothing to clean up
}
Member Function Documentation
getHumidityTimestamp()
unsigned long Si7021Sensor::getHumidityTimestamp () const override virtual
Get the timestamp of the last humidity reading.
Returns
Timestamp in milliseconds (from millis()).
Implements IHumiditySensor.
Definition at line 111 of file Si7021Sensor.cpp.
{
    return humTimestamp;
}
References humTimestamp.
getInterface()
void * Si7021Sensor::getInterface (InterfaceType type) const override virtual
Get the interface implementation for a specific type.
Parameters
type The interface type to get.
Returns
Pointer to the interface, or nullptr if not supported.
Reimplemented from BaseSensor.
Definition at line 172 of file Si7021Sensor.cpp.
{
    switch (type) {
        case InterfaceType::TEMPERATURE:
            return const_cast<ITemperatureSensor*>(static_cast<const ITemperatureSensor*>(this));
        case InterfaceType::HUMIDITY:
            return const_cast<IHumiditySensor*>(static_cast<const IHumiditySensor*>(this));
        default:
            return nullptr;
    }
}
References HUMIDITY, TEMPERATURE, and BaseSensor::type.
getSensorInfo()
String Si7021Sensor::getSensorInfo () const override virtual
Get detailed information about the sensor.
Returns
A string containing sensor information.
Implements ISensor.
Definition at line 134 of file Si7021Sensor.cpp.
{
    String info = "Sensor Name: " + name + "\n";
    info += "Type: Adafruit Si7021\n";
    info += "I2C Address: 0x" + String(i2cAddress, HEX) + "\n";
    info += "I2C Port: " + I2CManager::portToString(i2cPort) + "\n";
    info += "Connected: " + String(connected ? "Yes" : "No") + "\n";
    if (connected) {
        info += "Temperature: " + String(lastTemperature) + " C\n";
        info += "Humidity: " + String(lastHumidity) + " %\n";
        // Calculate time since last reading
        unsigned long now = millis();
        unsigned long tempAge = now - tempTimestamp;
        info += "Last Reading: " + String(tempAge / 1000.0) + " seconds ago\n";
        // Additional information about the sensor if accessible
        try {
            info += "Hardware Revision: " + String(si7021.getRevision()) + "\n";
            info += "Serial Number: 0x" + String(si7021.sernum_a, HEX) + "\n";
        } catch (...) {
            info += "Detailed sensor info unavailable\n";
        }
    }
    return info;
}
References BaseSensor::connected, i2cAddress, i2cPort, lastHumidity, lastTemperature, BaseSensor::name, I2CManager::portToString(), si7021, and tempTimestamp.
getTemperatureTimestamp()
unsigned long Si7021Sensor::getTemperatureTimestamp () const override virtual
Get the timestamp of the last temperature reading.
Returns
Timestamp in milliseconds (from millis()).
Implements ITemperatureSensor.
Definition at line 107 of file Si7021Sensor.cpp.
{
    return tempTimestamp;
}
References tempTimestamp.
initialize()
bool Si7021Sensor::initialize () override virtual
Initialize the sensor hardware.
Returns
true if initialization succeeded, false otherwise.
Implements ISensor.
Definition at line 21 of file Si7021Sensor.cpp.
{
    errorHandler->logError(INFO, "Initializing Si7021 sensor: " + name);
    if (!si7021.begin()) {
        errorHandler->logError(ERROR, "Failed to initialize Si7021 sensor: " + name);
        connected = false;
        return false;
    }
    connected = true;
    errorHandler->logError(INFO, "Si7021 sensor initialized successfully: " + name);
    // Read and log serial number for identification
    uint32_t serialNumber = si7021.sernum_a;
    errorHandler->logError(INFO, "Si7021 serial number: 0x" + String(serialNumber, HEX));
    // Get initial readings
    updateReadings();
    return true;
}
References BaseSensor::connected, ERROR, BaseSensor::errorHandler, INFO, BaseSensor::name, si7021, and updateReadings().
performSelfTest()
bool Si7021Sensor::performSelfTest () override virtual
Perform a self-test to verify the sensor is functioning properly.
Returns
true if the self-test passed, false otherwise.
Implements ISensor.
Definition at line 115 of file Si7021Sensor.cpp.
{
    // Reset the connected state before test
    connected = false;
    // Try to get both temperature and humidity readings
    bool success = updateReadings();
    if (success) {
        connected = true;
        errorHandler->logError(INFO, "Self-test passed for Si7021 sensor: " + name +
                " (Temperature: " + String(lastTemperature) + "C, Humidity: " +
                String(lastHumidity) + "%)");
    } else {
        errorHandler->logError(ERROR, "Self-test failed for Si7021 sensor: " + name);
    }
    return success;
}
References BaseSensor::connected, ERROR, BaseSensor::errorHandler, INFO, lastHumidity, lastTemperature, BaseSensor::name, and updateReadings().
readHumidity()
float Si7021Sensor::readHumidity () override virtual
Read the current humidity value from the sensor.
Returns
The relative humidity as a percentage (0-100), or NAN if reading failed.
Implements IHumiditySensor.
Definition at line 100 of file Si7021Sensor.cpp.
{
    if (!updateReadings()) {
        return NAN;
    }
    return lastHumidity;
}
References lastHumidity, and updateReadings().
readTemperature()
float Si7021Sensor::readTemperature () override virtual
Read the current temperature value from the sensor.
Returns
The temperature in degrees Celsius, or NAN if reading failed.
Implements ITemperatureSensor.
Definition at line 93 of file Si7021Sensor.cpp.
{
    if (!updateReadings()) {
        return NAN;
    }
    return lastTemperature;
}
References lastTemperature, and updateReadings().
reinitialize()
bool Si7021Sensor::reinitialize ()
Re-initialize the sensor after a communication failure.
Returns
true if re-initialization was successful
Definition at line 183 of file Si7021Sensor.cpp.
{
    errorHandler->logError(INFO, "Attempting to reinitialize Si7021 sensor: " + name);
    // Reset the connection state
    connected = false;
    // Add a small delay before reinitialization
    delay(50);
    // Try to initialize the sensor again
    bool success = si7021.begin();
    if (success) {
        connected = true;
        errorHandler->logError(INFO, "Successfully reinitialized Si7021 sensor: " + name);
        updateReadings();
    } else {
        errorHandler->logError(ERROR, "Failed to reinitialize Si7021 sensor: " + name);
    }
    return success;
}
References BaseSensor::connected, ERROR, BaseSensor::errorHandler, INFO, BaseSensor::name, si7021, and updateReadings().
supportsInterface()
bool Si7021Sensor::supportsInterface (InterfaceType type) const override virtual
Check if this sensor supports a specific interface.
Parameters
type The interface type to check for.
Returns
true if the sensor supports the interface, false otherwise.
Reimplemented from BaseSensor.
Definition at line 162 of file Si7021Sensor.cpp.
{
    switch (type) {
        case InterfaceType::TEMPERATURE:
        case InterfaceType::HUMIDITY:
            return true;
        default:
            return false;
    }
}
References HUMIDITY, TEMPERATURE, and BaseSensor::type.
updateReadings()
bool Si7021Sensor::updateReadings () const private
Update both temperature and humidity readings from the sensor.
Returns
True if the readings were successfully updated, false otherwise.
Definition at line 43 of file Si7021Sensor.cpp.
{
    if (!connected) {
        errorHandler->logError(ERROR, "Attempted to read from disconnected sensor: " + name);
        return false;
    }
    // Adding retries for more robustness
    const int MAX_RETRIES = 3;
    float temp = NAN;
    float humidity = NAN;
    bool success = false;
    for (int attempt = 0; attempt < MAX_RETRIES && !success; attempt++) {
        if (attempt > 0) {
            delay(50);
            errorHandler->logError(INFO, "Retrying Si7021 reading, attempt " + String(attempt+1) + " of " + String(MAX_RETRIES));
        }
        try {
            temp = si7021.readTemperature();
            if (!isnan(temp)) {
                delay(5);
                humidity = si7021.readHumidity();
                if (!isnan(humidity)) {
                    success = true;
                }
            }
        } catch (...) {
            errorHandler->logError(ERROR, "Exception during Si7021 reading for sensor: " + name);
            delay(20);
        }
    }
    if (!success) {
        errorHandler->logError(ERROR, "Failed to read from Si7021 sensor: " + name + " after " + String(MAX_RETRIES) + " retries");
        const_cast<Si7021Sensor*>(this)->connected = false;
        return false;
    }
    lastTemperature = temp;
    lastHumidity = humidity;
    unsigned long now = millis();
    tempTimestamp = now;
    humTimestamp = now;
    return true;
}
References BaseSensor::connected, ERROR, BaseSensor::errorHandler, humTimestamp, INFO, lastHumidity, lastTemperature, BaseSensor::name, si7021, Si7021Sensor(), and tempTimestamp.
Referenced by initialize(), performSelfTest(), readHumidity(), readTemperature(), and reinitialize().
Member Data Documentation
humTimestamp
unsigned long Si7021Sensor::humTimestamp mutable private
Timestamp of last humidity reading.
Definition at line 29 of file Si7021Sensor.h.
Referenced by getHumidityTimestamp(), Si7021Sensor(), and updateReadings().
i2cAddress
int Si7021Sensor::i2cAddress private
I2C address of the sensor.
Definition at line 25 of file Si7021Sensor.h.
Referenced by getSensorInfo(), and Si7021Sensor().
i2cManager
I2CManager* Si7021Sensor::i2cManager private
Reference to I2C manager.
Definition at line 24 of file Si7021Sensor.h.
Referenced by Si7021Sensor().
i2cPort
I2CPort Si7021Sensor::i2cPort private
I2C port identifier.
Definition at line 23 of file Si7021Sensor.h.
Referenced by getSensorInfo(), and Si7021Sensor().
lastHumidity
float Si7021Sensor::lastHumidity mutable private
Last humidity reading.
Definition at line 27 of file Si7021Sensor.h.
Referenced by getSensorInfo(), performSelfTest(), readHumidity(), Si7021Sensor(), and updateReadings().
lastTemperature
float Si7021Sensor::lastTemperature mutable private
Last temperature reading.
Definition at line 26 of file Si7021Sensor.h.
Referenced by getSensorInfo(), performSelfTest(), readTemperature(), Si7021Sensor(), and updateReadings().
si7021
Adafruit_Si7021 Si7021Sensor::si7021 mutable private
Underlying Adafruit driver (mutable for const methods)
Definition at line 21 of file Si7021Sensor.h.
Referenced by getSensorInfo(), initialize(), reinitialize(), Si7021Sensor(), and updateReadings().
tempTimestamp
unsigned long Si7021Sensor::tempTimestamp mutable private
Timestamp of last temperature reading.
Definition at line 28 of file Si7021Sensor.h.
Referenced by getSensorInfo(), getTemperatureTimestamp(), Si7021Sensor(), and updateReadings().
wire
TwoWire* Si7021Sensor::wire private
I2C bus for communication.
Definition at line 22 of file Si7021Sensor.h.
Referenced by Si7021Sensor().
The documentation for this class was generated from the following files:
src/sensors/Si7021Sensor.h
src/sensors/Si7021Sensor.cpp