GPower Environmental Monitor: SensorManager Class Reference
SensorManager Class Reference
Sensor Management
Manages sensor configuration, initialization, and readings This class serves as the central management system for all sensor operations:
#include <SensorManager.h>
Public Member Functions
SensorManager (ConfigManager *configMgr, I2CManager *i2c, ErrorHandler *err, SPIManager *spi=nullptr)
Constructor for SensorManager.
~SensorManager ()
Destructor - cleans up all sensors.
bool initializeSensors ()
Initialize all sensors from configuration Scans I2C and SPI buses for devices, then initializes sensors based on the current configuration.
bool reconfigureSensors (const String &configJson)
Reconfigure sensors based on new configuration Updates the sensor configuration based on new JSON settings, adding, removing, or reconfiguring sensors as needed.
int updateReadings ()
Update readings from all sensors Iterates through all sensors and updates their readings in the active cache buffer, then atomically swaps buffers.
TemperatureReading getTemperatureSafe (const String &sensorName)
Get temperature reading in a thread-safe manner.
HumidityReading getHumiditySafe (const String &sensorName)
Get humidity reading in a thread-safe manner.
void setMaxCacheAge (unsigned long maxAgeMs)
Set maximum age for cached readings.
unsigned long getMaxCacheAge () const
Get current maximum cache age.
const SensorRegistry & getRegistry () const
Get the sensor registry.
ISensor * findSensor (const String &name)
Find a sensor by name.
bool reconnectSensor (const String &sensorName)
Attempt to reconnect a disconnected sensor Tries to re-establish communication with a sensor that has been marked as disconnected.
int reconnectAllSensors ()
Attempt to reconnect all disconnected sensors.
Private Member Functions
std::map< String, SensorCache > & getActiveCache ()
Get the active buffer being written to.
const std::map< String, SensorCache > & getReadCache () const
Get the buffer for safe reading by other threads.
void compareConfigurations (const std::vector< SensorConfig > &oldConfigs, const std::vector< SensorConfig > &newConfigs, std::vector< SensorConfig > &toAdd, std::vector< String > &toRemove)
Compare old and new sensor configurations Determines which sensors need to be added or removed when reconfiguring the system.
bool testI2CCommunication (I2CPort port, int address)
Test communication with an I2C device.
bool testSPICommunication (int ssPin)
Test communication with an SPI device.
bool updateSensorCache (const String &sensorName)
Update readings for a single sensor.
Private Attributes
SensorRegistry registry
Registry of all active sensors.
SensorFactory factory
Factory for creating sensor instances.
ConfigManager * configManager
Configuration management system.
I2CManager * i2cManager
I2C bus management.
SPIManager * spiManager
SPI bus management.
ErrorHandler * errorHandler
Error reporting and handling.
unsigned long maxCacheAge = 5000
Maximum age of cached readings in milliseconds Readings older than this value will trigger a sensor refresh.
Double Buffering for Thread Safety
A double-buffering strategy to prevent race conditions between the sensor reading task and the communication task
std::atomic< bool > currentBufferIndex {false}
false = buffer A, true = buffer B
std::map< String, SensorCache > readingCacheA
First buffer for readings.
std::map< String, SensorCache > readingCacheB
Second buffer for readings.
Detailed Description
Manages sensor configuration, initialization, and readings This class serves as the central management system for all sensor operations:
Initializes sensors based on configuration
Provides thread-safe access to sensor readings
Caches sensor data to minimize read operations
Handles reconnection for failed sensors
Implements a double-buffering strategy for thread safety
Definition at line 54 of file SensorManager.h.
Constructor & Destructor Documentation
SensorManager()
SensorManager::SensorManager (ConfigManager * configMgr, I2CManager * i2c, ErrorHandler * err, SPIManager * spi = nullptr)
Constructor for SensorManager.
Parameters
configMgr Configuration manager
i2c I2C manager
err Error handler
spi Optional SPI manager
Definition at line 3 of file SensorManager.cpp.
        : registry(err),
        factory(err, i2c, spi),
        configManager(configMgr),
        i2cManager(i2c),
        spiManager(spi),
        errorHandler(err),
        maxCacheAge(5000) {  // Default 5-second cache age
        readingCacheA.clear();
        readingCacheB.clear();
}
References configManager, errorHandler, factory, i2cManager, maxCacheAge, readingCacheA, readingCacheB, registry, and spiManager.
~SensorManager()
SensorManager::~SensorManager ()
Destructor - cleans up all sensors.
Definition at line 15 of file SensorManager.cpp.
{
    // Clean up all sensor instances
    auto sensors = registry.clear();
    for (auto sensor : sensors) {
        delete sensor;
    }
}
References registry.
Member Function Documentation
compareConfigurations()
void SensorManager::compareConfigurations (const std::vector< SensorConfig > & oldConfigs, const std::vector< SensorConfig > & newConfigs, std::vector< SensorConfig > & toAdd, std::vector< String > & toRemove) private
Compare old and new sensor configurations Determines which sensors need to be added or removed when reconfiguring the system.
Parameters
oldConfigs Previous sensor configurations
newConfigs New sensor configurations
toAdd [out] Output vector of sensors to add
toRemove [out] Output vector of sensors to remove
Definition at line 230 of file SensorManager.cpp.
  {
    // Clear output vectors
    toAdd.clear();
    toRemove.clear();
    // Find sensors to remove (in old but not in new)
    for (const auto& oldConfig : oldConfigs) {
        bool found = false;
        for (const auto& newConfig : newConfigs) {
            if (oldConfig.name == newConfig.name) {
                found = true;
                break;
            }
        }
        if (!found) {
            toRemove.push_back(oldConfig.name);
        }
    }
    // Find sensors to add (in new but not in old)
    for (const auto& newConfig : newConfigs) {
        bool found = false;
        for (const auto& oldConfig : oldConfigs) {
            if (newConfig.name == oldConfig.name) {
                // Check if configuration changed
                if (newConfig.type != oldConfig.type ||
                    newConfig.address != oldConfig.address ||
                    newConfig.isSPI != oldConfig.isSPI ||
                    (!newConfig.isSPI && newConfig.i2cPort != oldConfig.i2cPort)) {
                    // Configuration changed, remove and re-add
                    toRemove.push_back(newConfig.name);
                    toAdd.push_back(newConfig);
                }
                found = true;
                break;
            }
        }
        if (!found) {
            toAdd.push_back(newConfig);
        }
    }
}
Referenced by reconfigureSensors().
findSensor()
ISensor * SensorManager::findSensor (const String & name)
Find a sensor by name.
Parameters
name Sensor name
Returns
Pointer to the sensor or nullptr if not found
Definition at line 412 of file SensorManager.cpp.
{
    return registry.getSensorByName(name);
}
References registry.
Referenced by reconnectSensor(), and updateSensorCache().
getActiveCache()
std::map< String, SensorCache > & SensorManager::getActiveCache () inline private
Get the active buffer being written to.
Returns
Reference to the active cache buffer
Definition at line 83 of file SensorManager.h.
{
         return currentBufferIndex.load() ? readingCacheB : readingCacheA;
     }
References currentBufferIndex, readingCacheA, and readingCacheB.
Referenced by updateSensorCache().
getHumiditySafe()
HumidityReading SensorManager::getHumiditySafe (const String & sensorName)
Get humidity reading in a thread-safe manner.
Parameters
sensorName Name of the sensor
Returns
Humidity reading with validity information
Definition at line 394 of file SensorManager.cpp.
{
    // Get the read buffer (not currently being written to)
    const std::map<String, SensorCache>& readCache = getReadCache();
    // Look for the sensor in the read cache
    auto it = readCache.find(sensorName);
    if (it != readCache.end() && it->second.humValid) {
        return HumidityReading(it->second.humidity, it->second.humTimestamp);
    }
    // No valid reading available
    return HumidityReading();
}
References getReadCache().
getMaxCacheAge()
unsigned long SensorManager::getMaxCacheAge () const inline
Get current maximum cache age.
Returns
Maximum age in milliseconds
Definition at line 203 of file SensorManager.h.
{ return maxCacheAge; }
References maxCacheAge.
getReadCache()
const std::map< String, SensorCache > & SensorManager::getReadCache () const inline private
Get the buffer for safe reading by other threads.
Returns
Const reference to the read cache buffer
Definition at line 91 of file SensorManager.h.
{
         return currentBufferIndex.load() ? readingCacheA : readingCacheB;
     }
References currentBufferIndex, readingCacheA, and readingCacheB.
Referenced by getHumiditySafe(), and getTemperatureSafe().
getRegistry()
const SensorRegistry & SensorManager::getRegistry () const
Get the sensor registry.
Returns
Reference to the sensor registry
Definition at line 408 of file SensorManager.cpp.
{
    return registry;
}
References registry.
Referenced by reconnectAllSensors().
getTemperatureSafe()
TemperatureReading SensorManager::getTemperatureSafe (const String & sensorName)
Get temperature reading in a thread-safe manner.
Parameters
sensorName Name of the sensor
Returns
Temperature reading with validity information
// Example usage:
TemperatureReading temp = sensorManager.getTemperatureSafe("SHT41_1");
if (temp.valid) {
    Serial.println("Temperature: " + String(temp.value) + " C");
}
Definition at line 380 of file SensorManager.cpp.
{
    // Get the read buffer (not currently being written to)
    const std::map<String, SensorCache>& readCache = getReadCache();
    // Look for the sensor in the read cache
    auto it = readCache.find(sensorName);
    if (it != readCache.end() && it->second.tempValid) {
        return TemperatureReading(it->second.temperature, it->second.tempTimestamp);
    }
    // No valid reading available
    return TemperatureReading();
}
References getReadCache().
initializeSensors()
bool SensorManager::initializeSensors ()
Initialize all sensors from configuration Scans I2C and SPI buses for devices, then initializes sensors based on the current configuration.
Returns
true if at least one sensor initialized successfully
Definition at line 23 of file SensorManager.cpp.
{
    // Initialize I2C buses if not already initialized
    if (!i2cManager->isPortInitialized(I2CPort::I2C0)) {
        if (!i2cManager->beginPort(I2CPort::I2C0)) {
            errorHandler->logError(ERROR, "Failed to initialize I2C0");
        } else {
            errorHandler->logError(INFO, "Initialized I2C0 bus");
        }
    }
    if (!i2cManager->isPortInitialized(I2CPort::I2C1)) {
        if (!i2cManager->beginPort(I2CPort::I2C1)) {
            errorHandler->logError(ERROR, "Failed to initialize I2C1");
        } else {
            errorHandler->logError(INFO, "Initialized I2C1 bus");
        }
    }
    // Initialize SPI if available
    if (spiManager && !spiManager->isInitialized()) {
        if (!spiManager->begin()) {
            errorHandler->logError(ERROR, "Failed to initialize SPI");
        } else {
            errorHandler->logError(INFO, "Initialized SPI bus");
        }
    }
    // Scan I2C buses for devices
    std::vector<int> foundAddressesI2C0;
    std::vector<int> foundAddressesI2C1;
    errorHandler->logError(INFO, "Scanning I2C0 bus for devices...");
    bool i2c0HasDevices = i2cManager->scanBus(I2CPort::I2C0, foundAddressesI2C0);
    errorHandler->logError(INFO, "Scanning I2C1 bus for devices...");
    bool i2c1HasDevices = i2cManager->scanBus(I2CPort::I2C1, foundAddressesI2C1);
    if (!i2c0HasDevices && !i2c1HasDevices) {
        errorHandler->logError(WARNING, "No I2C devices found on any bus - check wiring if using I2C sensors!");
    }
    // Get sensor configurations
    auto sensorConfigs = configManager->getSensorConfigs();
    bool atLeastOneInitialized = false;
    // Clear any existing sensors and update info
    auto existingSensors = registry.clear();
    for (auto sensor : existingSensors) {
        delete sensor;
    }
    // Create and initialize sensors
    for (const auto& config : sensorConfigs) {
        // Test communication before initializing sensor
        if (config.isSPI) {
            if (!spiManager) {
                errorHandler->logError(ERROR, "SPI manager not available for sensor: " + config.name);
                continue;
            }
            testSPICommunication(config.address);
        } else {
            testI2CCommunication(config.i2cPort, config.address);
        }
        // Create the sensor
        ISensor* sensor = factory.createSensor(config);
        if (!sensor) {
            errorHandler->logError(ERROR, "Failed to create sensor: " + config.name);
            continue;
        }
        // Initialize the sensor
        if (!sensor->initialize()) {
            errorHandler->logError(ERROR, "Failed to initialize sensor: " + config.name);
            delete sensor;
            continue;
        }
        // Register the sensor
        registry.registerSensor(sensor);
        errorHandler->logError(INFO, "Sensor added to system: " + config.name + " with polling rate: " +
                           String(config.pollingRate) + "ms");
        atLeastOneInitialized = true;
    }
    if (!atLeastOneInitialized) {
        errorHandler->logError(ERROR, "No sensors were initialized");
        return false;
    }
    return true;
}
References configManager, ERROR, errorHandler, factory, I2C0, I2C1, i2cManager, INFO, ISensor::initialize(), registry, spiManager, testI2CCommunication(), testSPICommunication(), and WARNING.
reconfigureSensors()
bool SensorManager::reconfigureSensors (const String & configJson)
Reconfigure sensors based on new configuration Updates the sensor configuration based on new JSON settings, adding, removing, or reconfiguring sensors as needed.
Parameters
configJson New configuration in JSON format
Returns
true if reconfiguration successful
Definition at line 117 of file SensorManager.cpp.
{
    // Parse the new configuration
    JsonDocument doc;
    DeserializationError error = deserializeJson(doc, configJson);
    if (error || doc.overflowed()) {
        errorHandler->logError(ERROR, "Failed to parse sensor configuration JSON: " +
                             String(error ? error.c_str() : "Memory overflow"));
        return false;
    }
    // Extract configurations from JSON
    std::vector<SensorConfig> oldConfigs = configManager->getSensorConfigs();
    std::vector<SensorConfig> newConfigs;
    // Extract I2C peripherals - UPDATED to use new naming scheme "Peripheral" in JSON
    if (doc["I2C Peripherals"].is<JsonArray>()) {
        JsonArray i2cPeripherals = doc["I2C Peripherals"].as<JsonArray>();
        for (JsonObject peripheral : i2cPeripherals) {
            SensorConfig config;
            // Required fields - UPDATED field names to match "Peripheral" naming in JSON
            config.name = peripheral["Peripheral Name"].as<String>();
            config.type = peripheral["Peripheral Type"].as<String>();
            config.address = peripheral["Address (HEX)"].as<int>();
            config.isSPI = false;
            // Optional fields with defaults
            config.i2cPort = I2CManager::stringToPort(
                peripheral["I2C Port"].isNull() ? "I2C0" : peripheral["I2C Port"].as<String>());
            config.pollingRate = peripheral["Polling Rate[1000 ms]"].isNull() ?
                1000 : peripheral["Polling Rate[1000 ms]"].as<uint32_t>();
            config.additional = peripheral["Additional"].isNull() ?
                "" : peripheral["Additional"].as<String>();
            // Apply polling rate limits
            config.pollingRate = constrain(config.pollingRate, 50, 300000);
            newConfigs.push_back(config);
        }
    }
    // Extract SPI peripherals - UPDATED to use new naming scheme "Peripheral" in JSON
    if (doc["SPI Peripherals"].is<JsonArray>()) {
        JsonArray spiPeripherals = doc["SPI Peripherals"].as<JsonArray>();
        for (JsonObject peripheral : spiPeripherals) {
            SensorConfig config;
            // Required fields - UPDATED field names to match "Peripheral" naming in JSON
            config.name = peripheral["Peripheral Name"].as<String>();
            config.type = peripheral["Peripheral Type"].as<String>();
            config.address = peripheral["SS Pin"].as<int>();
            config.isSPI = true;
            // Optional fields with defaults
            config.pollingRate = peripheral["Polling Rate[1000 ms]"].isNull() ?
                1000 : peripheral["Polling Rate[1000 ms]"].as<uint32_t>();
            config.additional = peripheral["Additional"].isNull() ?
                "" : peripheral["Additional"].as<String>();
            // Apply polling rate limits
            config.pollingRate = constrain(config.pollingRate, 50, 300000);
            newConfigs.push_back(config);
        }
    }
    // Determine which sensors to add and remove
    std::vector<SensorConfig> sensorsToAdd;
    std::vector<String> sensorsToRemove;
    compareConfigurations(oldConfigs, newConfigs, sensorsToAdd, sensorsToRemove);
    // Update the configuration in the ConfigManager
    configManager->disableNotifications(true);
    bool configUpdateSuccess = configManager->updateSensorConfigs(newConfigs);
    configManager->disableNotifications(false);
    if (!configUpdateSuccess) {
        errorHandler->logError(ERROR, "Failed to update sensor configuration");
        return false;
    }
    // Remove and add sensors as determined
    for (const auto& sensorName : sensorsToRemove) {
        ISensor* sensor = registry.unregisterSensor(sensorName);
        if (sensor) {
            errorHandler->logError(INFO, "Removing sensor: " + sensorName);
            delete sensor;
        }
    }
    bool allSuccess = true;
    for (const auto& config : sensorsToAdd) {
        errorHandler->logError(INFO, "Adding new sensor: " + config.name);
        // Create and initialize the sensor
        ISensor* sensor = factory.createSensor(config);
        if (!sensor || !sensor->initialize()) {
            if (sensor) delete sensor;
            errorHandler->logError(ERROR, "Failed to create/initialize sensor: " + config.name);
            allSuccess = false;
            continue;
        }
        // Register the successfully initialized sensor
        registry.registerSensor(sensor);
        errorHandler->logError(INFO, "Sensor added: " + config.name +
                            " with polling rate: " + String(config.pollingRate) + "ms");
    }
    return allSuccess;
}
References SensorConfig::additional, SensorConfig::address, compareConfigurations(), configManager, ERROR, errorHandler, factory, SensorConfig::i2cPort, INFO, ISensor::initialize(), SensorConfig::isSPI, SensorConfig::name, SensorConfig::pollingRate, registry, I2CManager::stringToPort(), and SensorConfig::type.
reconnectAllSensors()
int SensorManager::reconnectAllSensors ()
Attempt to reconnect all disconnected sensors.
Returns
Number of sensors successfully reconnected
The number of successfully reconnected sensors
Definition at line 515 of file SensorManager.cpp.
{
    int reconnectedCount = 0;
    auto registry = getRegistry();
    auto sensors = registry.getAllSensors();
    for (auto sensor : sensors) {
        if (!sensor->isConnected()) {
            if (reconnectSensor(sensor->getName())) {
                reconnectedCount++;
            }
        }
    }
    if (errorHandler && reconnectedCount > 0) {
        errorHandler->logError(INFO, "Reconnected " + String(reconnectedCount) + " sensors");
    }
    return reconnectedCount;
}
References errorHandler, getRegistry(), INFO, reconnectSensor(), and registry.
reconnectSensor()
bool SensorManager::reconnectSensor (const String & sensorName)
Attempt to reconnect a disconnected sensor Tries to re-establish communication with a sensor that has been marked as disconnected.
Parameters
sensorName Name of the sensor
Returns
true if reconnection successful
Definition at line 416 of file SensorManager.cpp.
{
    ISensor* sensor = findSensor(sensorName);
    if (!sensor) {
        if (errorHandler) {
            errorHandler->logError(WARNING, "Cannot reconnect - sensor not found: " + sensorName);
        }
        return false;
    }
    if (sensor->isConnected()) {
        // Sensor is already connected
        return true;
    }
    // Add timeout for reconnection attempt
    const unsigned long timeout = 500; // 500ms timeout
    unsigned long startTime = millis();
    if (errorHandler) {
        errorHandler->logError(INFO, "Attempting to reconnect sensor: " + sensorName);
    }
    // Check if we've exceeded the timeout at every step
    if (millis() - startTime >= timeout) {
        errorHandler->logError(WARNING, "Reconnection attempt timed out for sensor: " + sensorName);
        return false;
    }
    // Special handling for Si7021 sensors based on type string
    if (sensor->getTypeString().indexOf("Si7021") >= 0) {
        if (errorHandler) {
            errorHandler->logError(INFO, "Using specialized reconnection for Si7021 sensor");
        }
        // First try regular initialize with timeout check
        if (millis() - startTime < timeout - 100) {
            if (sensor->initialize()) {
                if (errorHandler) {
                    errorHandler->logError(INFO, "Successfully reconnected Si7021 sensor via initialize: " + sensorName);
                }
                return true;
            }
        }
        // Check timeout before attempting self-test
        if (millis() - startTime >= timeout) {
            errorHandler->logError(WARNING, "Reconnection initialization timed out for sensor: " + sensorName);
            return false;
        }
        // If that didn't work, try a more aggressive approach with self-test
        if (sensor->performSelfTest()) {
            if (errorHandler) {
                errorHandler->logError(INFO, "Successfully reconnected Si7021 sensor via self-test: " + sensorName);
            }
            return true;
        }
        // Still failed - report and return
        if (errorHandler) {
            errorHandler->logError(ERROR, "Failed to reconnect Si7021 sensor: " + sensorName);
        }
        return false;
    }
    // Generic reconnection attempt for other sensors with timeout check
    if (millis() - startTime < timeout - 200) {
        if (sensor->initialize()) {
            if (errorHandler) {
                errorHandler->logError(INFO, "Successfully reconnected sensor: " + sensorName);
            }
            return true;
        }
    }
    // Check timeout before attempting self-test
    if (millis() - startTime >= timeout) {
        errorHandler->logError(WARNING, "Reconnection initialization timed out for sensor: " + sensorName);
        return false;
    }
    // Try self-test if initialize didn't work
    if (sensor->performSelfTest()) {
        if (errorHandler) {
            errorHandler->logError(INFO, "Sensor reconnected via self-test: " + sensorName);
        }
        return true;
    }
    if (errorHandler) {
        errorHandler->logError(ERROR, "Failed to reconnect sensor: " + sensorName);
    }
    return false;
}
References ERROR, errorHandler, findSensor(), ISensor::getTypeString(), INFO, ISensor::initialize(), ISensor::isConnected(), ISensor::performSelfTest(), and WARNING.
Referenced by reconnectAllSensors().
setMaxCacheAge()
void SensorManager::setMaxCacheAge (unsigned long maxAgeMs) inline
Set maximum age for cached readings.
Parameters
maxAgeMs Maximum age in milliseconds
Definition at line 197 of file SensorManager.h.
{ maxCacheAge = maxAgeMs; }
References maxCacheAge.
testI2CCommunication()
bool SensorManager::testI2CCommunication (I2CPort port, int address) private
Test communication with an I2C device.
Parameters
port I2C port to use
address I2C address to test
Returns
true if communication successful
Definition at line 280 of file SensorManager.cpp.
{
    TwoWire* wire = i2cManager->getWire(port);
    if (!wire) {
        errorHandler->logError(ERROR, "Failed to get I2C bus for port " + I2CManager::portToString(port));
        return false;
    }
    wire->beginTransmission(address);
    byte error = wire->endTransmission();
    if (error == 0) {
        errorHandler->logError(INFO, "Direct I2C communication with address 0x" + String(address, HEX) +
                          " on port " + I2CManager::portToString(port) + " successful");
        return true;
    } else {
        errorHandler->logError(ERROR, "Direct I2C communication with address 0x" + String(address, HEX) +
                           " on port " + I2CManager::portToString(port) +
                           " failed with error: " + String(error));
        return false;
    }
}
References ERROR, errorHandler, i2cManager, INFO, and I2CManager::portToString().
Referenced by initializeSensors().
testSPICommunication()
bool SensorManager::testSPICommunication (int ssPin) private
Test communication with an SPI device.
Parameters
ssPin SPI slave select pin
Returns
true if communication successful
Definition at line 302 of file SensorManager.cpp.
{
    if (!spiManager || !spiManager->isInitialized()) {
        errorHandler->logError(ERROR, "SPI not initialized for SS pin test: " + String(ssPin));
        return false;
    }
    bool success = spiManager->testDevice(ssPin);
    if (success) {
        errorHandler->logError(INFO, "SPI communication test successful on SS pin: " + String(ssPin));
    } else {
        errorHandler->logError(WARNING, "SPI communication test inconclusive on SS pin: " + String(ssPin) +
                              " (may still work with specific device protocol)");
    }
    return true; // Return true even if the test is inconclusive, as it might still work with specific device
}
References ERROR, errorHandler, INFO, spiManager, and WARNING.
Referenced by initializeSensors().
updateReadings()
int SensorManager::updateReadings ()
Update readings from all sensors Iterates through all sensors and updates their readings in the active cache buffer, then atomically swaps buffers.
Returns
Number of sensors successfully updated
Definition at line 362 of file SensorManager.cpp.
{
    int successCount = 0;
    auto sensors = registry.getAllSensors();
    for (auto sensor : sensors) {
        if (sensor->isConnected()) {
            if (updateSensorCache(sensor->getName())) {
                successCount++;
            }
        }
    }
    // After updating all sensors, swap the buffers atomically
    currentBufferIndex.store(!currentBufferIndex.load());
    return successCount;
}
References currentBufferIndex, registry, and updateSensorCache().
updateSensorCache()
bool SensorManager::updateSensorCache (const String & sensorName) private
Update readings for a single sensor.
Parameters
sensorName Name of the sensor to update
Returns
true if update successful
Definition at line 320 of file SensorManager.cpp.
{
    ISensor* sensor = findSensor(sensorName);
    if (!sensor || !sensor->isConnected()) {
        return false;
    }
    // Get the active write buffer
    std::map<String, SensorCache>& activeCache = getActiveCache();
    SensorCache& cache = activeCache[sensorName];
    unsigned long currentTime = millis();
    bool updated = false;
    // Update temperature if supported
    if (sensor->supportsInterface(InterfaceType::TEMPERATURE)) {
        ITemperatureSensor* tempSensor =
            static_cast<ITemperatureSensor*>(sensor->getInterface(InterfaceType::TEMPERATURE));
        float temp = tempSensor->readTemperature();
        cache.temperature = temp;
        cache.tempTimestamp = currentTime;
        cache.tempValid = !isnan(temp);
        updated = true;
    }
    // Update humidity if supported
    if (sensor->supportsInterface(InterfaceType::HUMIDITY)) {
        IHumiditySensor* humSensor =
            static_cast<IHumiditySensor*>(sensor->getInterface(InterfaceType::HUMIDITY));
        float hum = humSensor->readHumidity();
        cache.humidity = hum;
        cache.humTimestamp = currentTime;
        cache.humValid = !isnan(hum);
        updated = true;
    }
    return updated;
}
References findSensor(), getActiveCache(), ISensor::getInterface(), HUMIDITY, SensorCache::humidity, SensorCache::humTimestamp, SensorCache::humValid, ISensor::isConnected(), IHumiditySensor::readHumidity(), ITemperatureSensor::readTemperature(), ISensor::supportsInterface(), TEMPERATURE, SensorCache::temperature, SensorCache::tempTimestamp, and SensorCache::tempValid.
Referenced by updateReadings().
Member Data Documentation
configManager
ConfigManager* SensorManager::configManager private
Configuration management system.
Definition at line 58 of file SensorManager.h.
Referenced by initializeSensors(), reconfigureSensors(), and SensorManager().
currentBufferIndex
std::atomic<bool> SensorManager::currentBufferIndex {false} private
false = buffer A, true = buffer B
Definition at line 68 of file SensorManager.h.
{false};
Referenced by getActiveCache(), getReadCache(), and updateReadings().
errorHandler
ErrorHandler* SensorManager::errorHandler private
Error reporting and handling.
Definition at line 61 of file SensorManager.h.
Referenced by initializeSensors(), reconfigureSensors(), reconnectAllSensors(), reconnectSensor(), SensorManager(), testI2CCommunication(), and testSPICommunication().
factory
SensorFactory SensorManager::factory private
Factory for creating sensor instances.
Definition at line 57 of file SensorManager.h.
Referenced by initializeSensors(), reconfigureSensors(), and SensorManager().
i2cManager
I2CManager* SensorManager::i2cManager private
I2C bus management.
Definition at line 59 of file SensorManager.h.
Referenced by initializeSensors(), SensorManager(), and testI2CCommunication().
maxCacheAge
unsigned long SensorManager::maxCacheAge = 5000 private
Maximum age of cached readings in milliseconds Readings older than this value will trigger a sensor refresh.
Definition at line 77 of file SensorManager.h.
Referenced by getMaxCacheAge(), SensorManager(), and setMaxCacheAge().
readingCacheA
std::map<String, SensorCache> SensorManager::readingCacheA private
First buffer for readings.
Definition at line 69 of file SensorManager.h.
Referenced by getActiveCache(), getReadCache(), and SensorManager().
readingCacheB
std::map<String, SensorCache> SensorManager::readingCacheB private
Second buffer for readings.
Definition at line 70 of file SensorManager.h.
Referenced by getActiveCache(), getReadCache(), and SensorManager().
registry
SensorRegistry SensorManager::registry private
Registry of all active sensors.
Definition at line 56 of file SensorManager.h.
Referenced by findSensor(), getRegistry(), initializeSensors(), reconfigureSensors(), reconnectAllSensors(), SensorManager(), updateReadings(), and ~SensorManager().
spiManager
SPIManager* SensorManager::spiManager private
SPI bus management.
Definition at line 60 of file SensorManager.h.
Referenced by initializeSensors(), SensorManager(), and testSPICommunication().
The documentation for this class was generated from the following files:
src/managers/SensorManager.h
src/managers/SensorManager.cpp