GPower Environmental Monitor: ISensor Class Reference
ISensor Class Reference abstract
Base interface for all sensors Defines core functionality that all sensors must implement, regardless of the specific measurements they provide.
#include <ISensor.h>
Public Member Functions
virtual ~ISensor ()=default
Virtual destructor.
virtual String getName () const =0
Get the sensor's name.
virtual bool isConnected () const =0
Check if sensor is connected and working.
virtual bool initialize ()=0
Initialize sensor hardware.
virtual bool performSelfTest ()=0
Perform sensor self-test.
virtual String getSensorInfo () const =0
Get detailed sensor information.
virtual String getTypeString () const =0
Get sensor type as string.
virtual bool supportsInterface (InterfaceType type) const =0
Check if sensor supports a specific interface.
virtual void * getInterface (InterfaceType type) const =0
Get interface implementation.
Detailed Description
Base interface for all sensors Defines core functionality that all sensors must implement, regardless of the specific measurements they provide.
Definition at line 19 of file ISensor.h.
Constructor & Destructor Documentation
~ISensor()
virtual ISensor::~ISensor () virtual default
Virtual destructor.
Member Function Documentation
getInterface()
virtual void * ISensor::getInterface (InterfaceType type) const pure virtual
Get interface implementation.
Parameters
type Interface type to get
Returns
void pointer to interface or nullptr if not supported
Implemented in BaseSensor, PT100Sensor, SHT41Sensor, and Si7021Sensor.
Referenced by SensorRegistry::getInterfaceFrom(), and SensorManager::updateSensorCache().
getName()
virtual String ISensor::getName () const pure virtual
Get the sensor's name.
Returns
String identifier for the sensor
Implemented in BaseSensor.
Referenced by SensorRegistry::registerSensor().
getSensorInfo()
virtual String ISensor::getSensorInfo () const pure virtual
Get detailed sensor information.
Returns
Multi-line string with sensor details
Implemented in PT100Sensor, SHT41Sensor, and Si7021Sensor.
getTypeString()
virtual String ISensor::getTypeString () const pure virtual
Get sensor type as string.
Returns
String representation of sensor type
Implemented in BaseSensor.
Referenced by SensorManager::reconnectSensor().
initialize()
virtual bool ISensor::initialize () pure virtual
Initialize sensor hardware.
Returns
true if initialization successful
Implemented in PT100Sensor, SHT41Sensor, and Si7021Sensor.
Referenced by SensorManager::initializeSensors(), SensorManager::reconfigureSensors(), and SensorManager::reconnectSensor().
isConnected()
virtual bool ISensor::isConnected () const pure virtual
Check if sensor is connected and working.
Returns
true if operational, false otherwise
Implemented in BaseSensor.
Referenced by CommunicationManager::collectSensorReadings(), SensorManager::reconnectSensor(), and SensorManager::updateSensorCache().
performSelfTest()
virtual bool ISensor::performSelfTest () pure virtual
Perform sensor self-test.
Returns
true if self-test passed
Implemented in PT100Sensor, SHT41Sensor, and Si7021Sensor.
Referenced by SensorManager::reconnectSensor().
supportsInterface()
virtual bool ISensor::supportsInterface (InterfaceType type) const pure virtual
Check if sensor supports a specific interface.
Parameters
type Interface type to check
Returns
true if interface is supported
Implemented in BaseSensor, PT100Sensor, SHT41Sensor, and Si7021Sensor.
Referenced by CommunicationManager::collectSensorReadings(), SensorRegistry::getInterfaceFrom(), and SensorManager::updateSensorCache().
The documentation for this class was generated from the following file:
src/sensors/interfaces/ISensor.h