GPower Environmental Monitor: SPIManager Class Reference
SPIManager Class Reference
Communication » SPI Management
Class for managing SPI communications with sensors This class provides a centralized management system for SPI communications, handling bus initialization, device selection, and transaction management.
#include <SPIManager.h>
Public Member Functions
int mapLogicalToPhysicalPin (int logicalPin)
Map a logical SS pin index to a physical pin number Converts a logical pin index (0, 1, 2, etc.) to the corresponding physical GPIO pin number from the Constants::Pins::SPI::SS_PINS array.
SPIManager (ErrorHandler *err)
Constructor for SPIManager.
~SPIManager ()
Destructor.
bool begin (int mosi=DEFAULT_SPI_MOSI_PIN, int miso=DEFAULT_SPI_MISO_PIN, int sck=DEFAULT_SPI_SCK_PIN)
Initialize the SPI bus Initializes the SPI bus with the specified pin assignments.
bool isInitialized () const
Check if SPI bus is initialized.
bool registerSSPin (int ssPin)
Register an SS pin for use with SPI Configures the specified pin as an output for use as an SPI slave select.
bool beginTransaction (int ssPin, SPISettings settings=SPISettings())
Begin an SPI transaction Begins an SPI transaction with the specified SS pin and settings.
void endTransaction (int ssPin)
End an SPI transaction Ends the current SPI transaction and deselects the specified SS pin.
uint8_t transfer (uint8_t data)
Transfer a single byte over SPI.
void transfer (uint8_t *buffer, size_t size)
Transfer multiple bytes over SPI.
bool testDevice (int ssPin)
Test if an SPI device is present Performs a simple test to check if a device is responding on the specified SS pin.
SPIClass & getSPI ()
Get the SPI class instance.
int getMisoPin () const
int getSckPin () const
Get the SCK pin.
Private Attributes
ErrorHandler * errorHandler
Error handler for logging and error reporting.
bool initialized
Flag indicating if SPI has been initialized.
SPISettings defaultSettings
Default settings for SPI communications.
int mosiPin
SPI pin definitions.
int misoPin
int sckPin
std::vector< int > ssPins
List of all slave select pins.
Detailed Description
Class for managing SPI communications with sensors This class provides a centralized management system for SPI communications, handling bus initialization, device selection, and transaction management.
Definition at line 35 of file SPIManager.h.
Constructor & Destructor Documentation
SPIManager()
SPIManager::SPIManager (ErrorHandler * err)
Constructor for SPIManager.
Parameters
err Pointer to the error handler for logging
Definition at line 3 of file SPIManager.cpp.
    : errorHandler(err),
      initialized(false),
      mosiPin(DEFAULT_SPI_MOSI_PIN),
      misoPin(DEFAULT_SPI_MISO_PIN),
      sckPin(DEFAULT_SPI_SCK_PIN),
      defaultSettings(1000000, MSBFIRST, SPI_MODE0) {
}
References DEFAULT_SPI_MISO_PIN, DEFAULT_SPI_MOSI_PIN, DEFAULT_SPI_SCK_PIN, defaultSettings, errorHandler, initialized, misoPin, mosiPin, and sckPin.
~SPIManager()
SPIManager::~SPIManager ()
Destructor.
Definition at line 12 of file SPIManager.cpp.
{
    // Nothing to clean up
}
Member Function Documentation
begin()
bool SPIManager::begin (int mosi = DEFAULT_SPI_MOSI_PIN, int miso = DEFAULT_SPI_MISO_PIN, int sck = DEFAULT_SPI_SCK_PIN)
Initialize the SPI bus Initializes the SPI bus with the specified pin assignments.
Parameters
mosi The MOSI pin number (default: Constants::Pins::SPI::MOSI)
miso The MISO pin number (default: Constants::Pins::SPI::MISO)
sck The SCK pin number (default: Constants::Pins::SPI::SCK)
Returns
true if initialization succeeded, false otherwise
Definition at line 16 of file SPIManager.cpp.
{
    if (initialized) {
        // Already initialized
        return true;
    }
    mosiPin = mosi;
    misoPin = miso;
    sckPin = sck;
    // Initialize SPI
    SPI.begin(sckPin, misoPin, mosiPin);
    initialized = true;
    errorHandler->logError(INFO, "SPI initialized with pins MOSI:" + String(mosiPin) +
                          " MISO:" + String(misoPin) +
                          " SCK:" + String(sckPin));
    return true;
}
References errorHandler, INFO, initialized, misoPin, mosiPin, and sckPin.
beginTransaction()
bool SPIManager::beginTransaction (int ssPin, SPISettings settings = SPISettings())
Begin an SPI transaction Begins an SPI transaction with the specified SS pin and settings.
Parameters
ssPin The SS pin to use (logical index or physical pin)
settings The SPI settings to use (default: SPISettings())
Returns
true if transaction initialization succeeded, false otherwise
Definition at line 64 of file SPIManager.cpp.
{
    if (!initialized) {
        errorHandler->logError(ERROR, "SPI not initialized");
        return false;
    }
    // Map logical index to physical pin if needed
    int physicalPin = mapLogicalToPhysicalPin(ssPin);
    // Make sure the SS pin is registered
    bool pinFound = false;
    for (int pin : ssPins) {
        if (pin == physicalPin) {
            pinFound = true;
            break;
        }
    }
    if (!pinFound) {
        // Auto-register the pin if not found
        registerSSPin(ssPin);
        physicalPin = mapLogicalToPhysicalPin(ssPin);
    }
    // Begin transaction
    SPI.beginTransaction(settings);
    digitalWrite(physicalPin, LOW); // Active state
    return true;
}
References ERROR, errorHandler, initialized, mapLogicalToPhysicalPin(), registerSSPin(), and ssPins.
Referenced by testDevice().
endTransaction()
void SPIManager::endTransaction (int ssPin)
End an SPI transaction Ends the current SPI transaction and deselects the specified SS pin.
Parameters
ssPin The SS pin to deselect (logical index or physical pin)
Definition at line 95 of file SPIManager.cpp.
{
    // Map logical index to physical pin if needed
    int physicalPin = mapLogicalToPhysicalPin(ssPin);
    digitalWrite(physicalPin, HIGH); // Inactive state
    SPI.endTransaction();
}
References mapLogicalToPhysicalPin().
Referenced by testDevice().
getMisoPin()
int SPIManager::getMisoPin () const inline
  @brief Get the MOSI pin
Returns
The MISO pin number
Definition at line 163 of file SPIManager.h.
{ return misoPin; }
References misoPin.
getSckPin()
int SPIManager::getSckPin () const inline
Get the SCK pin.
Returns
The SCK pin number
Definition at line 169 of file SPIManager.h.
{ return sckPin; }
References sckPin.
getSPI()
SPIClass & SPIManager::getSPI ()
Get the SPI class instance.
Returns
Reference to the SPI instance
Definition at line 139 of file SPIManager.cpp.
{
    return SPI;
}
isInitialized()
bool SPIManager::isInitialized () const
Check if SPI bus is initialized.
Returns
true if SPI is initialized, false otherwise
Definition at line 37 of file SPIManager.cpp.
{
    return initialized;
}
References initialized.
mapLogicalToPhysicalPin()
int SPIManager::mapLogicalToPhysicalPin (int logicalPin) inline
Map a logical SS pin index to a physical pin number Converts a logical pin index (0, 1, 2, etc.) to the corresponding physical GPIO pin number from the Constants::Pins::SPI::SS_PINS array.
Parameters
logicalPin The logical SS pin index
Returns
The physical pin number
Definition at line 70 of file SPIManager.h.
{
         size_t arraySize = sizeof(Constants::Pins::SPI::SS_PINS) / sizeof(int);
         if (logicalPin >= 0 && logicalPin < arraySize) {
             return Constants::Pins::SPI::SS_PINS[logicalPin];
         }
         return logicalPin; // Return unchanged if out of range
     }
References Constants::Pins::SPI::SS_PINS.
Referenced by beginTransaction(), endTransaction(), PT100Sensor::PT100Sensor(), and registerSSPin().
registerSSPin()
bool SPIManager::registerSSPin (int ssPin)
Register an SS pin for use with SPI Configures the specified pin as an output for use as an SPI slave select.
Parameters
ssPin The SS pin to register (logical index or physical pin)
Returns
true if registration succeeded, false otherwise
Definition at line 41 of file SPIManager.cpp.
{
    // Map logical index to physical pin if needed
    int physicalPin = mapLogicalToPhysicalPin(ssPin);
    // Check if pin is already registered
    for (int pin : ssPins) {
        if (pin == physicalPin) {
            errorHandler->logError(INFO, "SS pin " + String(physicalPin) + " already registered");
            return true; // Already registered, so technically successful
        }
    }
    // Configure the pin as output
    pinMode(physicalPin, OUTPUT);
    digitalWrite(physicalPin, HIGH); // Inactive state
    // Add to the list
    ssPins.push_back(physicalPin);
    errorHandler->logError(INFO, "Registered SS pin " + String(physicalPin));
    return true;
}
References errorHandler, INFO, mapLogicalToPhysicalPin(), and ssPins.
Referenced by beginTransaction().
testDevice()
bool SPIManager::testDevice (int ssPin)
Test if an SPI device is present Performs a simple test to check if a device is responding on the specified SS pin.
Parameters
ssPin The SS pin to test (logical index or physical pin)
Returns
true if device appears to be present, false otherwise
Note
This test may not be reliable for all devices
Definition at line 111 of file SPIManager.cpp.
{
    // This is a generic test that may not work for all devices.
    // Some devices require specific commands to respond correctly.
    if (!initialized) {
        errorHandler->logError(ERROR, "SPI not initialized");
        return false;
    }
    bool success = beginTransaction(ssPin);
    if (!success) {
        return false;
    }
    // Transfer a byte and check if we get something back
    // This may not be reliable for all devices, but it's a starting point
    uint8_t response = transfer(0xFF); // Send dummy byte
    endTransaction(ssPin);
    errorHandler->logError(INFO, "SPI test on SS pin " + String(ssPin) +
                          " returned response: 0x" + String(response, HEX));
    // For a real test, we would need device-specific logic here
    // For now, just return true as a placeholder
    return true;
}
References beginTransaction(), endTransaction(), ERROR, errorHandler, INFO, initialized, and transfer().
transfer() [1/2]
void SPIManager::transfer (uint8_t * buffer, size_t size)
Transfer multiple bytes over SPI.
Parameters
buffer Pointer to the data buffer (in-place transfer)
size Number of bytes to transfer
Definition at line 107 of file SPIManager.cpp.
{
    SPI.transfer(buffer, size);
}
transfer() [2/2]
uint8_t SPIManager::transfer (uint8_t data)
Transfer a single byte over SPI.
Parameters
data The byte to send
Returns
The byte received during the transfer
Definition at line 103 of file SPIManager.cpp.
{
    return SPI.transfer(data);
}
Referenced by testDevice().
Member Data Documentation
defaultSettings
SPISettings SPIManager::defaultSettings private
Default settings for SPI communications.
Definition at line 60 of file SPIManager.h.
Referenced by SPIManager().
errorHandler
ErrorHandler* SPIManager::errorHandler private
Error handler for logging and error reporting.
Definition at line 40 of file SPIManager.h.
Referenced by begin(), beginTransaction(), registerSSPin(), SPIManager(), and testDevice().
initialized
bool SPIManager::initialized private
Flag indicating if SPI has been initialized.
Definition at line 45 of file SPIManager.h.
Referenced by begin(), beginTransaction(), isInitialized(), SPIManager(), and testDevice().
misoPin
int SPIManager::misoPin private
Definition at line 52 of file SPIManager.h.
Referenced by begin(), getMisoPin(), and SPIManager().
mosiPin
int SPIManager::mosiPin private
SPI pin definitions.
Definition at line 51 of file SPIManager.h.
Referenced by begin(), and SPIManager().
sckPin
int SPIManager::sckPin private
Definition at line 53 of file SPIManager.h.
Referenced by begin(), getSckPin(), and SPIManager().
ssPins
std::vector<int> SPIManager::ssPins private
List of all slave select pins.
Definition at line 54 of file SPIManager.h.
Referenced by beginTransaction(), and registerSSPin().
The documentation for this class was generated from the following files:
src/managers/SPIManager.h
src/managers/SPIManager.cpp