GPower Environmental Monitor: SensorFactory Class Reference
SensorFactory Class Reference
Sensors » Sensor Factory
Factory class for creating sensors based on configuration This class is responsible for creating instances of different sensor types based on configuration data.
#include <SensorFactory.h>
Public Member Functions
SensorFactory (ErrorHandler *err, I2CManager *i2c, SPIManager *spi=nullptr)
Constructor for SensorFactory.
void setSPIManager (SPIManager *spi)
Set the SPI manager.
ISensor * createSensor (const SensorConfig &config)
Create a sensor instance based on the provided configuration Factory method that creates and returns an appropriate sensor instance based on the configuration type and parameters.
Private Member Functions
template<typename SensorType>
ISensor * createI2CSensor (const SensorConfig &config)
Create a sensor using the template method pattern.
ISensor * createPT100Sensor (const SensorConfig &config)
Create a PT100 RTD sensor instance Special case for PT100 sensors that need additional parameters.
void parseAdditionalPT100Settings (const String &additional, float &refResistor, int &wireMode)
Parse additional settings for PT100 sensors.
Private Attributes
ErrorHandler * errorHandler
Error handler for logging.
I2CManager * i2cManager
I2C manager for communication.
SPIManager * spiManager
SPI manager for communication.
Detailed Description
Factory class for creating sensors based on configuration This class is responsible for creating instances of different sensor types based on configuration data.
It encapsulates knowledge of specific sensor implementations and their initialization requirements.
Definition at line 34 of file SensorFactory.h.
Constructor & Destructor Documentation
SensorFactory()
SensorFactory::SensorFactory (ErrorHandler * err, I2CManager * i2c, SPIManager * spi = nullptr)
Constructor for SensorFactory.
Parameters
err Pointer to the error handler for logging
i2c Pointer to the I2C manager for I2C communication
spi Pointer to the SPI manager for SPI communication (optional)
Definition at line 6 of file SensorFactory.cpp.
    : errorHandler(err), i2cManager(i2c), spiManager(spi) {
}
References errorHandler, i2cManager, and spiManager.
Member Function Documentation
createI2CSensor()
template<typename SensorType> template ISensor * SensorFactory::createI2CSensor< Si7021Sensor > (const SensorConfig & config) private
Create a sensor using the template method pattern.
Template Parameters
SensorType The type of sensor to create
Parameters
config The sensor configuration
Returns
Pointer to the created sensor, or nullptr if creation failed
Definition at line 16 of file SensorFactory.cpp.
{
    if (config.isSPI) {
        errorHandler->logError(ERROR, "Sensor type does not support SPI interface");
        return nullptr;
    }
    // Initialize the appropriate I2C bus if not already done
    if (!i2cManager->isPortInitialized(config.i2cPort)) {
        if (!i2cManager->beginPort(config.i2cPort)) {
            errorHandler->logError(ERROR, "Failed to initialize I2C port " +
                                I2CManager::portToString(config.i2cPort) +
                                " for sensor " + config.name);
            return nullptr;
        }
    }
    // Get the appropriate TwoWire instance
    TwoWire* wire = i2cManager->getWire(config.i2cPort);
    if (!wire) {
        errorHandler->logError(ERROR, "Failed to get I2C bus for port " +
                            I2CManager::portToString(config.i2cPort));
        return nullptr;
    }
    // Create sensor with the specified configuration
    return new SensorType(config.name, config.address, wire, i2cManager, config.i2cPort, errorHandler);
}
References SensorConfig::address, ERROR, errorHandler, i2cManager, SensorConfig::i2cPort, SensorConfig::isSPI, SensorConfig::name, and I2CManager::portToString().
Referenced by createSensor().
createPT100Sensor()
ISensor * SensorFactory::createPT100Sensor (const SensorConfig & config) private
Create a PT100 RTD sensor instance Special case for PT100 sensors that need additional parameters.
Parameters
config The sensor configuration
Returns
Pointer to the created sensor, or nullptr if creation failed
Definition at line 83 of file SensorFactory.cpp.
{
    if (!config.isSPI) {
        errorHandler->logError(ERROR, "PT100 RTD requires SPI interface");
        return nullptr;
    }
    // Check SPI initialization
    if (!spiManager || !spiManager->isInitialized()) {
        errorHandler->logError(ERROR, "SPI not initialized for PT100 sensor: " + config.name);
        return nullptr;
    }
    // Default values
    float referenceResistor = 430.0;
    int wireMode = 3;
    // Parse additional settings if provided
    parseAdditionalPT100Settings(config.additional, referenceResistor, wireMode);
    // Map the logical pin to physical pin
    int physicalSsPin = config.address;
    // Calculate the size of the SS_PINS array instead of using MAX_SS_PINS
    size_t numSsPins = sizeof(Constants::Pins::SPI::SS_PINS) / sizeof(int);
    if (config.address >= 0 && config.address < numSsPins) {
        physicalSsPin = spiManager->mapLogicalToPhysicalPin(config.address);
    }
    // Create the sensor with hardware SPI
    errorHandler->logError(INFO, "Creating PT100 sensor with physical SS pin: " + String(physicalSsPin) +
                         ", Ref: " + String(referenceResistor) +
                         ", Wire mode: " + String(wireMode));
    return new PT100Sensor(
        config.name,
        physicalSsPin,
        spiManager,
        errorHandler,
        referenceResistor,
        wireMode
    );
}
References SensorConfig::additional, SensorConfig::address, ERROR, errorHandler, INFO, SensorConfig::isSPI, SensorConfig::name, parseAdditionalPT100Settings(), spiManager, and Constants::Pins::SPI::SS_PINS.
Referenced by createSensor().
createSensor()
ISensor * SensorFactory::createSensor (const SensorConfig & config)
Create a sensor instance based on the provided configuration Factory method that creates and returns an appropriate sensor instance based on the configuration type and parameters.
Parameters
config The sensor configuration
Returns
Pointer to the created sensor, or nullptr if creation failed
Definition at line 49 of file SensorFactory.cpp.
{
    SensorType type = sensorTypeFromString(config.type);
    // Log sensor creation
    errorHandler->logError(INFO, "Creating sensor: " + config.name + " of type " + config.type +
                     (config.isSPI ?
                      " (SPI, SS Pin: " + String(config.address) + ")" :
                      " (I2C, Port: " + I2CManager::portToString(config.i2cPort) +
                      ", Address: 0x" + String(config.address, HEX) + ")"));
    // Check SPI manager for SPI sensors
    if (config.isSPI && !spiManager) {
        errorHandler->logError(ERROR, "SPI manager not provided for SPI sensor: " + config.name);
        return nullptr;
    }
    // Create sensor based on type
    switch (type) {
        case SensorType::SHT41:
            return createI2CSensor<SHT41Sensor>(config);
        case SensorType::SI7021:
            return createI2CSensor<Si7021Sensor>(config);
        case SensorType::PT100_RTD:
            return createPT100Sensor(config);  // Special case for PT100
        default:
            errorHandler->logError(ERROR, "Unsupported sensor type: " + config.type);
            return nullptr;
    }
}
References SensorConfig::address, createI2CSensor(), createPT100Sensor(), ERROR, errorHandler, SensorConfig::i2cPort, INFO, SensorConfig::isSPI, SensorConfig::name, I2CManager::portToString(), PT100_RTD, sensorTypeFromString(), SHT41, SI7021, spiManager, and SensorConfig::type.
parseAdditionalPT100Settings()
void SensorFactory::parseAdditionalPT100Settings (const String & additional, float & refResistor, int & wireMode) private
Parse additional settings for PT100 sensors.
Parameters
additional The additional settings string
refResistor Output parameter for reference resistor value
wireMode Output parameter for wire mode
Definition at line 127 of file SensorFactory.cpp.
{
    if (additional.length() == 0) return;
    // Parse wire mode
    if (additional.indexOf("Wire mode:") >= 0 ||
        additional.indexOf("wire mode:") >= 0 ||
        additional.indexOf("Wire:") >= 0) {
        int pos = additional.indexOf("-wire");
        if (pos > 0) {
            for (int i = pos - 1; i >= 0; i--) {
                if (isDigit(additional.charAt(i))) {
                    char digitChar = additional.charAt(i);
                    if (digitChar >= '2' && digitChar <= '4') {
                        wireMode = digitChar - '0';
                        break;
                    }
                }
            }
        }
    }
    // Parse reference resistor value
    if (additional.indexOf("Ref:") >= 0 ||
        additional.indexOf("ref:") >= 0 ||
        additional.indexOf("Resistor:") >= 0) {
        int pos = additional.indexOf("Ref:") >= 0 ? additional.indexOf("Ref:") + 4 :
                (additional.indexOf("ref:") >= 0 ? additional.indexOf("ref:") + 4 :
                additional.indexOf("Resistor:") + 10);
        if (pos > 0) {
            String valStr = "";
            for (unsigned int i = pos; i < additional.length() &&
                (isDigit(additional.charAt(i)) || additional.charAt(i) == '.'); i++) {
                valStr += additional.charAt(i);
            }
            if (valStr.length() > 0) {
                float val = valStr.toFloat();
                if (val > 100.0 && val < 10000.0) {
                    refResistor = val;
                }
            }
        }
    }
}
Referenced by createPT100Sensor().
setSPIManager()
void SensorFactory::setSPIManager (SPIManager * spi)
Set the SPI manager.
Parameters
spi Pointer to the SPI manager
Definition at line 10 of file SensorFactory.cpp.
{
    spiManager = spi;
}
References spiManager.
Member Data Documentation
errorHandler
ErrorHandler* SensorFactory::errorHandler private
Error handler for logging.
Definition at line 39 of file SensorFactory.h.
Referenced by createI2CSensor(), createPT100Sensor(), createSensor(), and SensorFactory().
i2cManager
I2CManager* SensorFactory::i2cManager private
I2C manager for communication.
Definition at line 44 of file SensorFactory.h.
Referenced by createI2CSensor(), and SensorFactory().
spiManager
SPIManager* SensorFactory::spiManager private
SPI manager for communication.
Definition at line 49 of file SensorFactory.h.
Referenced by createPT100Sensor(), createSensor(), SensorFactory(), and setSPIManager().
The documentation for this class was generated from the following files:
src/sensors/SensorFactory.h
src/sensors/SensorFactory.cpp