@startuml
[*] --> SetupMode : System Initialization

state SetupMode : Yellow Solid
note right of SetupMode : Initial state during system startup

SetupMode --> NormalMode : Initialization Complete

state NormalMode {
  state Idle : Green Dim
  state ReadingPulse : Green Bright
  
  Idle --> ReadingPulse : Sensor Reading
  ReadingPulse --> Idle : After 100ms
}

NormalMode --> WarningMode : Warning Event
state WarningMode : Orange Bright
WarningMode --> NormalMode : After 2 seconds

NormalMode --> ErrorMode : Error Event
state ErrorMode : Red Bright
ErrorMode --> NormalMode : After 2 seconds

NormalMode --> IdentifyMode : Identify Command
state IdentifyMode {
  state BlueOn : Blue Bright
  state BlueOff : LED Off
  
  [*] --> BlueOn
  BlueOn --> BlueOff : After 250ms
  BlueOff --> BlueOn : After 250ms
  BlueOn --> [*] : After 10 flashes
}
note top of IdentifyMode : Blue flashing to identify device\namong multiple units

IdentifyMode --> NormalMode

NormalMode --> FatalErrorMode : Fatal Error
state FatalErrorMode : Red Solid Permanent
note bottom of FatalErrorMode : Terminal state - requires\nsystem restart to exit
@enduml