@startuml
start

repeat
  if (Time to read sensors?) then (yes)
    :Get all registered sensors;
    
    if (Any disconnected sensors?) then (yes)
      if (5s since last recovery attempt?) then (yes)
        :Attempt sensor reconnection;
        :Update recovery timestamp;
      else (no)
        :Skip recovery attempt;
      endif
    endif
    
    :Iterate through sensors;
    while (More sensors?) is (yes)
      if (Sensor connected?) then (yes)
        :Update sensor readings;
        
        if (Temperature supported?) then (yes)
          :Store temperature reading;
        endif
        
        if (Humidity supported?) then (yes)
          :Store humidity reading;
        endif
      endif
      :Move to next sensor;
    endwhile (no)
    
    :Atomically swap read/write buffers;
    :Signal LED for reading activity;
    :Update reading timestamp;
  else (no)
    :Wait 50ms;
  endif
repeat while (Continue monitoring?) is (yes)

stop
@enduml