@startuml
hide footbox
mainframe **cd** UC2: Establishing Connection
skinparam sequenceMessageAlign center

actor "Test Engineer" as Engineer
participant "LabVIEW" as LabVIEW
participant "ESP32" as Board

Engineer -> LabVIEW: Launch with drivers
Engineer -> LabVIEW: Identify Environmental Monitor.vi
LabVIEW -> Board: ~*IDN?
Board -> LabVIEW: ID
LabVIEW -> Engineer: ID and COM port

Engineer -> LabVIEW: Select COM port
LabVIEW -> Board: Connect.vi

@enduml